// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TagUid, TagUidT } from '../../oww/ntag/tag-uid.js';


export class NewTagRequest implements flatbuffers.IUnpackableObject<NewTagRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NewTagRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNewTagRequest(bb:flatbuffers.ByteBuffer, obj?:NewTagRequest):NewTagRequest {
  return (obj || new NewTagRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNewTagRequest(bb:flatbuffers.ByteBuffer, obj?:NewTagRequest):NewTagRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NewTagRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tokenId(obj?:TagUid):TagUid|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TagUid()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startNewTagRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTokenId(builder:flatbuffers.Builder, tokenIdOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, tokenIdOffset, 0);
}

static endNewTagRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNewTagRequest(builder:flatbuffers.Builder, tokenIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  NewTagRequest.startNewTagRequest(builder);
  NewTagRequest.addTokenId(builder, tokenIdOffset);
  return NewTagRequest.endNewTagRequest(builder);
}

serialize():Uint8Array {
  return this.bb!.bytes();
}

static deserialize(buffer: Uint8Array):NewTagRequest {
  return NewTagRequest.getRootAsNewTagRequest(new flatbuffers.ByteBuffer(buffer))
}

unpack(): NewTagRequestT {
  return new NewTagRequestT(
    (this.tokenId() !== null ? this.tokenId()!.unpack() : null)
  );
}


unpackTo(_o: NewTagRequestT): void {
  _o.tokenId = (this.tokenId() !== null ? this.tokenId()!.unpack() : null);
}
}

export class NewTagRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public tokenId: TagUidT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return NewTagRequest.createNewTagRequest(builder,
    (this.tokenId !== null ? this.tokenId!.pack(builder) : 0)
  );
}
}
