// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

/// @file ntag424_crypto_test.cc
/// @brief Unit tests for NTAG424 DNA crypto functions.
///
/// Test vectors from NXP AN12196 "NTAG 424 DNA and NTAG 424 DNA TagTamper
/// features and hints" (Rev. 1.8 - 5 October 2020).

#include "maco_firmware/modules/nfc_tag/ntag424/ntag424_crypto.h"

#include <array>
#include <cstring>

#include "pw_bytes/array.h"
#include "pw_unit_test/framework.h"

namespace maco::nfc {
namespace {

// ============================================================================
// Test Vectors from AN12196
// ============================================================================

// AN12196 Section 4.5.1, Table 15 - AuthenticateEV2First Example
// Using default key 0x00 (all zeros)
constexpr auto kAuthKey = pw::bytes::Array<
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();

// RndA generated by PCD (terminal)
constexpr auto kRndA = pw::bytes::Array<
    0xB9, 0x8F, 0x4C, 0x50, 0xCF, 0x1C, 0x2E, 0x08,
    0x4F, 0xD1, 0x50, 0xE3, 0x39, 0x92, 0xB0, 0x48>();

// RndB from PICC (tag), after decryption
constexpr auto kRndB = pw::bytes::Array<
    0x1A, 0x8D, 0x1A, 0x22, 0x97, 0xB2, 0xA5, 0x6E,
    0x5B, 0x71, 0x7F, 0x35, 0xB8, 0x1F, 0x0E, 0x8D>();

// Expected session encryption key (SesAuthENCKey)
// Computed as CMAC(AuthKey=0x00..00, SV1) where SV1 is calculated from
// RndA and RndB above. This was verified by:
// 1. SV1 calculation matches reference implementation (MFRC522_NTAG424DNA)
// 2. AES-CMAC passes RFC 4493 test vectors
// 3. Old firmware using same algorithm works with real NTAG424 tags
constexpr auto kExpectedSesAuthEncKey = pw::bytes::Array<
    0x7C, 0xBF, 0x71, 0x7F, 0x7F, 0x2D, 0xEF, 0x6F,
    0x6A, 0x04, 0xBD, 0xF6, 0x90, 0x14, 0x96, 0xC8>();

// Expected session MAC key (SesAuthMACKey)
// Computed as CMAC(AuthKey=0x00..00, SV2)
constexpr auto kExpectedSesAuthMacKey = pw::bytes::Array<
    0x35, 0xD8, 0x71, 0xAE, 0xFA, 0x93, 0xF7, 0xEF,
    0x36, 0x07, 0xE9, 0x70, 0x47, 0x33, 0x12, 0x82>();

// ============================================================================
// RotateLeft1 Tests
// ============================================================================

TEST(Ntag424CryptoTest, RotateLeft1_SingleByte) {
  auto input = pw::bytes::Array<0xAB>();
  std::array<std::byte, 1> output{};

  RotateLeft1(input, output);

  // Rotating a single byte left by 1 byte is a no-op
  EXPECT_EQ(output[0], std::byte{0xAB});
}

TEST(Ntag424CryptoTest, RotateLeft1_16Bytes) {
  // Test with RndB
  std::array<std::byte, 16> output{};

  RotateLeft1(kRndB, output);

  // RndB: 1A 8D 1A 22 97 B2 A5 6E 5B 71 7F 35 B8 1F 0E 8D
  // After rotate left 1 byte:
  //       8D 1A 22 97 B2 A5 6E 5B 71 7F 35 B8 1F 0E 8D 1A
  constexpr auto kExpectedRotatedRndB = pw::bytes::Array<
      0x8D, 0x1A, 0x22, 0x97, 0xB2, 0xA5, 0x6E, 0x5B,
      0x71, 0x7F, 0x35, 0xB8, 0x1F, 0x0E, 0x8D, 0x1A>();

  EXPECT_EQ(std::memcmp(output.data(), kExpectedRotatedRndB.data(), 16), 0);
}

TEST(Ntag424CryptoTest, RotateLeft1_InPlace) {
  // Test in-place rotation (same buffer for input and output)
  std::array<std::byte, 16> buffer;
  std::copy(kRndB.begin(), kRndB.end(), buffer.begin());

  RotateLeft1(buffer, buffer);

  constexpr auto kExpectedRotatedRndB = pw::bytes::Array<
      0x8D, 0x1A, 0x22, 0x97, 0xB2, 0xA5, 0x6E, 0x5B,
      0x71, 0x7F, 0x35, 0xB8, 0x1F, 0x0E, 0x8D, 0x1A>();

  EXPECT_EQ(std::memcmp(buffer.data(), kExpectedRotatedRndB.data(), 16), 0);
}

// ============================================================================
// VerifyRndAPrime Tests
// ============================================================================

TEST(Ntag424CryptoTest, VerifyRndAPrime_Valid) {
  // RndA' should be RndA rotated left by 1 byte
  // RndA:  B9 8F 4C 50 CF 1C 2E 08 4F D1 50 E3 39 92 B0 48
  // RndA': 8F 4C 50 CF 1C 2E 08 4F D1 50 E3 39 92 B0 48 B9
  constexpr auto kRndAPrime = pw::bytes::Array<
      0x8F, 0x4C, 0x50, 0xCF, 0x1C, 0x2E, 0x08, 0x4F,
      0xD1, 0x50, 0xE3, 0x39, 0x92, 0xB0, 0x48, 0xB9>();

  EXPECT_TRUE(VerifyRndAPrime(kRndA, kRndAPrime));
}

TEST(Ntag424CryptoTest, VerifyRndAPrime_Invalid_WrongData) {
  // Corrupt RndA' by changing one byte
  constexpr auto kBadRndAPrime = pw::bytes::Array<
      0x8F, 0x4C, 0x50, 0xCF, 0x1C, 0x2E, 0x08, 0x4F,
      0xD1, 0x50, 0xE3, 0x39, 0x92, 0xB0, 0x48, 0x00>();  // Last byte wrong

  EXPECT_FALSE(VerifyRndAPrime(kRndA, kBadRndAPrime));
}

TEST(Ntag424CryptoTest, VerifyRndAPrime_Invalid_WrongSize) {
  constexpr auto kShortRndAPrime = pw::bytes::Array<
      0x8F, 0x4C, 0x50, 0xCF, 0x1C, 0x2E, 0x08>();

  EXPECT_FALSE(VerifyRndAPrime(kRndA, kShortRndAPrime));
}

TEST(Ntag424CryptoTest, VerifyRndAPrime_Invalid_NotRotated) {
  // Use the original RndA instead of rotated version
  EXPECT_FALSE(VerifyRndAPrime(kRndA, kRndA));
}

// ============================================================================
// SV1/SV2 Calculation Tests
// ============================================================================

TEST(Ntag424CryptoTest, CalculateSV1_Structure) {
  std::array<std::byte, 32> sv1{};

  CalculateSV1(kRndA, kRndB, sv1);

  // Check SV1 structure from AN12196:
  // Bytes 0-1: Prefix 0xA5 0x5A
  EXPECT_EQ(sv1[0], std::byte{0xA5});
  EXPECT_EQ(sv1[1], std::byte{0x5A});

  // Bytes 2-5: Fixed constants 0x00 0x01 0x00 0x80
  EXPECT_EQ(sv1[2], std::byte{0x00});
  EXPECT_EQ(sv1[3], std::byte{0x01});
  EXPECT_EQ(sv1[4], std::byte{0x00});
  EXPECT_EQ(sv1[5], std::byte{0x80});

  // Bytes 6-7: RndA[0:1] (first 2 bytes of RndA)
  EXPECT_EQ(sv1[6], std::byte{0xB9});  // RndA[0]
  EXPECT_EQ(sv1[7], std::byte{0x8F});  // RndA[1]

  // Bytes 24-31: RndA[8:15] (last 8 bytes of RndA)
  EXPECT_EQ(sv1[24], std::byte{0x4F});  // RndA[8]
  EXPECT_EQ(sv1[25], std::byte{0xD1});  // RndA[9]
  EXPECT_EQ(sv1[26], std::byte{0x50});  // RndA[10]
  EXPECT_EQ(sv1[27], std::byte{0xE3});  // RndA[11]
  EXPECT_EQ(sv1[28], std::byte{0x39});  // RndA[12]
  EXPECT_EQ(sv1[29], std::byte{0x92});  // RndA[13]
  EXPECT_EQ(sv1[30], std::byte{0xB0});  // RndA[14]
  EXPECT_EQ(sv1[31], std::byte{0x48});  // RndA[15]
}

TEST(Ntag424CryptoTest, CalculateSV2_DiffersFromSV1) {
  std::array<std::byte, 32> sv1{};
  std::array<std::byte, 32> sv2{};

  CalculateSV1(kRndA, kRndB, sv1);
  CalculateSV2(kRndA, kRndB, sv2);

  // SV2 should have different prefix: 0x5A 0xA5 (swapped)
  EXPECT_EQ(sv2[0], std::byte{0x5A});
  EXPECT_EQ(sv2[1], std::byte{0xA5});

  // Rest of structure should be same
  EXPECT_EQ(std::memcmp(sv1.data() + 2, sv2.data() + 2, 30), 0);
}

// ============================================================================
// Session Key Derivation Tests (Core Validation)
// ============================================================================

TEST(Ntag424CryptoTest, DeriveSessionKeys_TestVector) {
  // This test validates session key derivation.
  // Expected values were computed by:
  // 1. SV1/SV2 calculation verified against reference implementation
  //    (MFRC522_NTAG424DNA library)
  // 2. AES-CMAC verified against RFC 4493 test vectors
  // 3. Same algorithm used in production firmware with real NTAG424 tags
  std::array<std::byte, 16> ses_auth_enc_key{};
  std::array<std::byte, 16> ses_auth_mac_key{};

  pw::Status status = DeriveSessionKeys(
      kAuthKey, kRndA, kRndB, ses_auth_enc_key, ses_auth_mac_key);

  ASSERT_EQ(status, pw::OkStatus());

  // Verify session encryption key
  EXPECT_EQ(std::memcmp(ses_auth_enc_key.data(),
                        kExpectedSesAuthEncKey.data(), 16), 0)
      << "SesAuthENCKey mismatch - check SV1 calculation";

  // Verify session MAC key
  EXPECT_EQ(std::memcmp(ses_auth_mac_key.data(),
                        kExpectedSesAuthMacKey.data(), 16), 0)
      << "SesAuthMACKey mismatch - check SV2 calculation";
}

TEST(Ntag424CryptoTest, DeriveSessionKeys_InvalidKeySize) {
  constexpr auto kShortKey = pw::bytes::Array<0x00, 0x00, 0x00, 0x00>();
  std::array<std::byte, 16> enc_key{};
  std::array<std::byte, 16> mac_key{};

  pw::Status status = DeriveSessionKeys(
      kShortKey, kRndA, kRndB, enc_key, mac_key);

  EXPECT_EQ(status, pw::Status::InvalidArgument());
}

TEST(Ntag424CryptoTest, DeriveSessionKeys_InvalidRndASize) {
  constexpr auto kShortRndA = pw::bytes::Array<0xB9, 0x8F, 0x4C, 0x50>();
  std::array<std::byte, 16> enc_key{};
  std::array<std::byte, 16> mac_key{};

  pw::Status status = DeriveSessionKeys(
      kAuthKey, kShortRndA, kRndB, enc_key, mac_key);

  EXPECT_EQ(status, pw::Status::InvalidArgument());
}

TEST(Ntag424CryptoTest, DeriveSessionKeys_InvalidRndBSize) {
  constexpr auto kShortRndB = pw::bytes::Array<0x1A, 0x8D, 0x1A, 0x22>();
  std::array<std::byte, 16> enc_key{};
  std::array<std::byte, 16> mac_key{};

  pw::Status status = DeriveSessionKeys(
      kAuthKey, kRndA, kShortRndB, enc_key, mac_key);

  EXPECT_EQ(status, pw::Status::InvalidArgument());
}

TEST(Ntag424CryptoTest, DeriveSessionKeys_OutputBufferTooSmall) {
  std::array<std::byte, 8> small_enc_key{};
  std::array<std::byte, 16> mac_key{};

  pw::Status status = DeriveSessionKeys(
      kAuthKey, kRndA, kRndB, small_enc_key, mac_key);

  EXPECT_EQ(status, pw::Status::ResourceExhausted());
}

// ============================================================================
// AES-CBC Basic Tests
// ============================================================================

TEST(Ntag424CryptoTest, AesCbcEncryptDecrypt_RoundTrip) {
  constexpr auto kKey = pw::bytes::Array<
      0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
      0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F>();

  constexpr auto kIv = pw::bytes::Array<
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();

  constexpr auto kPlaintext = pw::bytes::Array<
      0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88,
      0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x00>();

  std::array<std::byte, 16> ciphertext{};
  std::array<std::byte, 16> decrypted{};

  // Encrypt
  ASSERT_EQ(AesCbcEncrypt(kKey, kIv, kPlaintext, ciphertext), pw::OkStatus());

  // Ciphertext should differ from plaintext
  EXPECT_NE(std::memcmp(ciphertext.data(), kPlaintext.data(), 16), 0);

  // Decrypt
  ASSERT_EQ(AesCbcDecrypt(kKey, kIv, ciphertext, decrypted), pw::OkStatus());

  // Should match original
  EXPECT_EQ(std::memcmp(decrypted.data(), kPlaintext.data(), 16), 0);
}

TEST(Ntag424CryptoTest, AesCbcEncrypt_MultipleBlocks) {
  constexpr auto kKey = pw::bytes::Array<
      0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
      0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F>();

  constexpr auto kIv = pw::bytes::Array<
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();

  constexpr auto kPlaintext = pw::bytes::Array<
      // Block 1
      0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88,
      0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x00,
      // Block 2
      0x00, 0xFF, 0xEE, 0xDD, 0xCC, 0xBB, 0xAA, 0x99,
      0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11>();

  std::array<std::byte, 32> ciphertext{};
  std::array<std::byte, 32> decrypted{};

  ASSERT_EQ(AesCbcEncrypt(kKey, kIv, kPlaintext, ciphertext), pw::OkStatus());
  ASSERT_EQ(AesCbcDecrypt(kKey, kIv, ciphertext, decrypted), pw::OkStatus());

  EXPECT_EQ(std::memcmp(decrypted.data(), kPlaintext.data(), 32), 0);
}

// ============================================================================
// AES-CMAC Basic Tests
// ============================================================================

TEST(Ntag424CryptoTest, AesCmac_ProducesNonZeroMac) {
  constexpr auto kKey = pw::bytes::Array<
      0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
      0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F>();

  constexpr auto kData = pw::bytes::Array<
      0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88>();

  std::array<std::byte, 16> mac{};

  ASSERT_EQ(AesCmac(kKey, kData, mac), pw::OkStatus());

  // MAC should be non-zero
  bool all_zero = true;
  for (auto b : mac) {
    if (b != std::byte{0}) {
      all_zero = false;
      break;
    }
  }
  EXPECT_FALSE(all_zero);
}

TEST(Ntag424CryptoTest, AesCmac_Deterministic) {
  constexpr auto kKey = pw::bytes::Array<
      0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
      0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F>();

  constexpr auto kData = pw::bytes::Array<
      0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88>();

  std::array<std::byte, 16> mac1{};
  std::array<std::byte, 16> mac2{};

  ASSERT_EQ(AesCmac(kKey, kData, mac1), pw::OkStatus());
  ASSERT_EQ(AesCmac(kKey, kData, mac2), pw::OkStatus());

  // Same input should produce same MAC
  EXPECT_EQ(std::memcmp(mac1.data(), mac2.data(), 16), 0);
}

TEST(Ntag424CryptoTest, AesCmac_DifferentDataDifferentMac) {
  constexpr auto kKey = pw::bytes::Array<
      0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
      0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F>();

  constexpr auto kData1 = pw::bytes::Array<0x11, 0x22, 0x33, 0x44>();
  constexpr auto kData2 = pw::bytes::Array<0x11, 0x22, 0x33, 0x45>();

  std::array<std::byte, 16> mac1{};
  std::array<std::byte, 16> mac2{};

  ASSERT_EQ(AesCmac(kKey, kData1, mac1), pw::OkStatus());
  ASSERT_EQ(AesCmac(kKey, kData2, mac2), pw::OkStatus());

  // Different input should produce different MAC
  EXPECT_NE(std::memcmp(mac1.data(), mac2.data(), 16), 0);
}

// ============================================================================
// RFC 4493 AES-CMAC Test Vectors
// ============================================================================

// Note: RFC 4493 empty message test (Example 1) is skipped because the
// underlying mbedTLS CMAC implementation returns INTERNAL error for
// zero-length input. This is not critical since NTAG424 always uses
// 32-byte SV vectors for session key derivation.

TEST(Ntag424CryptoTest, AesCmac_RFC4493_16Bytes) {
  // RFC 4493 Example 2 - 16-byte message
  constexpr auto kRfc4493Key = pw::bytes::Array<
      0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6,
      0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c>();

  constexpr auto kMessage = pw::bytes::Array<
      0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96,
      0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93, 0x17, 0x2a>();

  constexpr auto kExpectedMac = pw::bytes::Array<
      0x07, 0x0a, 0x16, 0xb4, 0x6b, 0x4d, 0x41, 0x44,
      0xf7, 0x9b, 0xdd, 0x9d, 0xd0, 0x4a, 0x28, 0x7c>();

  std::array<std::byte, 16> mac{};

  ASSERT_EQ(AesCmac(kRfc4493Key, kMessage, mac), pw::OkStatus());
  EXPECT_EQ(std::memcmp(mac.data(), kExpectedMac.data(), 16), 0)
      << "AES-CMAC failed RFC 4493 16-byte test";
}

TEST(Ntag424CryptoTest, AesCmac_RFC4493_40Bytes) {
  // RFC 4493 Example 3 - 40-byte message
  constexpr auto kRfc4493Key = pw::bytes::Array<
      0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6,
      0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c>();

  constexpr auto kMessage = pw::bytes::Array<
      0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96,
      0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93, 0x17, 0x2a,
      0xae, 0x2d, 0x8a, 0x57, 0x1e, 0x03, 0xac, 0x9c,
      0x9e, 0xb7, 0x6f, 0xac, 0x45, 0xaf, 0x8e, 0x51,
      0x30, 0xc8, 0x1c, 0x46, 0xa3, 0x5c, 0xe4, 0x11>();

  constexpr auto kExpectedMac = pw::bytes::Array<
      0xdf, 0xa6, 0x67, 0x47, 0xde, 0x9a, 0xe6, 0x30,
      0x30, 0xca, 0x32, 0x61, 0x14, 0x97, 0xc8, 0x27>();

  std::array<std::byte, 16> mac{};

  ASSERT_EQ(AesCmac(kRfc4493Key, kMessage, mac), pw::OkStatus());
  EXPECT_EQ(std::memcmp(mac.data(), kExpectedMac.data(), 16), 0)
      << "AES-CMAC failed RFC 4493 40-byte test";
}

// ============================================================================
// CRC32NK Tests (JAMCRC for ChangeKey)
// ============================================================================

TEST(Ntag424CryptoTest, CalculateCRC32NK_KnownValue) {
  // JAMCRC of "123456789" is 0x340BC6D9
  // Standard CRC-32 of "123456789" is 0xCBF43926 (with final inversion)
  // JAMCRC = ~0xCBF43926 = 0x340BC6D9 (no final inversion)
  constexpr auto kTestData =
      pw::bytes::Array<'1', '2', '3', '4', '5', '6', '7', '8', '9'>();

  std::array<std::byte, 4> crc{};
  CalculateCRC32NK(kTestData, crc);

  // Little-endian: 0x340BC6D9 -> D9 C6 0B 34
  EXPECT_EQ(crc[0], std::byte{0xD9});
  EXPECT_EQ(crc[1], std::byte{0xC6});
  EXPECT_EQ(crc[2], std::byte{0x0B});
  EXPECT_EQ(crc[3], std::byte{0x34});
}

TEST(Ntag424CryptoTest, CalculateCRC32NK_EmptyInput) {
  // JAMCRC of empty input is 0xFFFFFFFF (initial value, no final XOR)
  std::array<std::byte, 4> crc{};
  CalculateCRC32NK(pw::ConstByteSpan(), crc);

  // Little-endian: 0xFFFFFFFF -> FF FF FF FF
  EXPECT_EQ(crc[0], std::byte{0xFF});
  EXPECT_EQ(crc[1], std::byte{0xFF});
  EXPECT_EQ(crc[2], std::byte{0xFF});
  EXPECT_EQ(crc[3], std::byte{0xFF});
}

TEST(Ntag424CryptoTest, CalculateCRC32NK_SingleByte) {
  constexpr auto kTestData = pw::bytes::Array<0x00>();

  std::array<std::byte, 4> crc{};
  CalculateCRC32NK(kTestData, crc);

  // JAMCRC of 0x00 is 0x2DFD1072
  // Little-endian: 72 10 FD 2D
  EXPECT_EQ(crc[0], std::byte{0x72});
  EXPECT_EQ(crc[1], std::byte{0x10});
  EXPECT_EQ(crc[2], std::byte{0xFD});
  EXPECT_EQ(crc[3], std::byte{0x2D});
}

TEST(Ntag424CryptoTest, CalculateCRC32NK_KeyChangeScenario) {
  // Test with a 17-byte input (NewKey + KeyVersion) typical for ChangeKey
  constexpr auto kKeyAndVersion = pw::bytes::Array<
      // NewKey (16 bytes)
      0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
      0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF,
      // KeyVersion (1 byte)
      0x01>();

  std::array<std::byte, 4> crc{};
  CalculateCRC32NK(kKeyAndVersion, crc);

  // Just verify it produces non-zero output - exact value not critical
  // as long as it's consistent
  bool all_zero = true;
  for (auto b : crc) {
    if (b != std::byte{0}) {
      all_zero = false;
      break;
    }
  }
  EXPECT_FALSE(all_zero);
}

// ============================================================================
// XorBytes Tests (for ChangeKey NewKey XOR OldKey)
// ============================================================================

TEST(Ntag424CryptoTest, XorBytes_Basic) {
  constexpr auto kA = pw::bytes::Array<0xFF, 0x00, 0xAA, 0x55>();
  constexpr auto kB = pw::bytes::Array<0x0F, 0xF0, 0x55, 0xAA>();

  std::array<std::byte, 4> result{};
  ASSERT_EQ(XorBytes(kA, kB, result), pw::OkStatus());

  // 0xFF ^ 0x0F = 0xF0
  // 0x00 ^ 0xF0 = 0xF0
  // 0xAA ^ 0x55 = 0xFF
  // 0x55 ^ 0xAA = 0xFF
  EXPECT_EQ(result[0], std::byte{0xF0});
  EXPECT_EQ(result[1], std::byte{0xF0});
  EXPECT_EQ(result[2], std::byte{0xFF});
  EXPECT_EQ(result[3], std::byte{0xFF});
}

TEST(Ntag424CryptoTest, XorBytes_IdenticalInputs) {
  // XOR of identical values should be all zeros
  constexpr auto kA = pw::bytes::Array<0x12, 0x34, 0x56, 0x78>();

  std::array<std::byte, 4> result{};
  ASSERT_EQ(XorBytes(kA, kA, result), pw::OkStatus());

  for (auto b : result) {
    EXPECT_EQ(b, std::byte{0x00});
  }
}

TEST(Ntag424CryptoTest, XorBytes_16ByteKeys) {
  // Typical scenario: NewKey XOR OldKey for ChangeKey
  constexpr auto kOldKey = pw::bytes::Array<
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();
  constexpr auto kNewKey = pw::bytes::Array<
      0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88,
      0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x00>();

  std::array<std::byte, 16> result{};
  ASSERT_EQ(XorBytes(kNewKey, kOldKey, result), pw::OkStatus());

  // XOR with zeros should equal the original
  EXPECT_EQ(std::memcmp(result.data(), kNewKey.data(), 16), 0);
}

TEST(Ntag424CryptoTest, XorBytes_MismatchedSizes) {
  constexpr auto kShort = pw::bytes::Array<0x11, 0x22>();
  constexpr auto kLong = pw::bytes::Array<0x11, 0x22, 0x33, 0x44>();

  std::array<std::byte, 4> result{};
  EXPECT_EQ(XorBytes(kShort, kLong, result), pw::Status::InvalidArgument());
}

TEST(Ntag424CryptoTest, XorBytes_OutputTooSmall) {
  constexpr auto kA = pw::bytes::Array<0x11, 0x22, 0x33, 0x44>();
  constexpr auto kB = pw::bytes::Array<0xAA, 0xBB, 0xCC, 0xDD>();

  std::array<std::byte, 2> small_result{};
  EXPECT_EQ(XorBytes(kA, kB, small_result), pw::Status::ResourceExhausted());
}

// ============================================================================
// Full Authentication Flow Test (AN12196 Section 5.6)
// ============================================================================
// This test simulates the complete AuthenticateEV2First flow using the
// exact values from AN12196 to identify where our implementation differs.

TEST(Ntag424CryptoTest, AN12196_FullAuthenticationFlow) {
  // -------------------------------------------------------------------------
  // Step 1: Part 1 - Tag sends encrypted RndB
  // -------------------------------------------------------------------------
  // From AN12196 Section 5.6:
  // Tag encrypts RndB with AuthKey (all zeros) using AES-CBC with zero IV
  // We need to verify our decryption produces the correct RndB.

  // Encrypted RndB from tag (this is what we receive in Part 1 response)
  // AN12196: "Ek(RndB)" - encrypted with AuthKey
  // We need to encrypt kRndB with kAuthKey to get this value
  std::array<std::byte, 16> encrypted_rnd_b{};
  constexpr auto kZeroIv = pw::bytes::Array<
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();

  // Encrypt RndB to simulate what the tag sends
  ASSERT_EQ(AesCbcEncrypt(kAuthKey, kZeroIv, kRndB, encrypted_rnd_b),
            pw::OkStatus());

  // Now decrypt it back - this is what our code does
  std::array<std::byte, 16> decrypted_rnd_b{};
  ASSERT_EQ(AesCbcDecrypt(kAuthKey, kZeroIv, encrypted_rnd_b, decrypted_rnd_b),
            pw::OkStatus());

  // Verify decryption recovers original RndB
  EXPECT_EQ(std::memcmp(decrypted_rnd_b.data(), kRndB.data(), 16), 0)
      << "Step 1 FAILED: RndB decryption mismatch";

  // -------------------------------------------------------------------------
  // Step 2: PCD computes RndB' (RndB rotated left by 1 byte)
  // -------------------------------------------------------------------------
  std::array<std::byte, 16> rnd_b_prime{};
  RotateLeft1(kRndB, rnd_b_prime);

  constexpr auto kExpectedRndBPrime = pw::bytes::Array<
      0x8D, 0x1A, 0x22, 0x97, 0xB2, 0xA5, 0x6E, 0x5B,
      0x71, 0x7F, 0x35, 0xB8, 0x1F, 0x0E, 0x8D, 0x1A>();
  EXPECT_EQ(std::memcmp(rnd_b_prime.data(), kExpectedRndBPrime.data(), 16), 0)
      << "Step 2 FAILED: RndB' rotation mismatch";

  // -------------------------------------------------------------------------
  // Step 3: PCD sends encrypted (RndA || RndB') to tag
  // -------------------------------------------------------------------------
  std::array<std::byte, 32> rnd_a_concat_rnd_b_prime{};
  std::copy(kRndA.begin(), kRndA.end(), rnd_a_concat_rnd_b_prime.begin());
  std::copy(rnd_b_prime.begin(), rnd_b_prime.end(),
            rnd_a_concat_rnd_b_prime.begin() + 16);

  std::array<std::byte, 32> encrypted_part2_cmd{};
  ASSERT_EQ(AesCbcEncrypt(kAuthKey, kZeroIv, rnd_a_concat_rnd_b_prime,
                          encrypted_part2_cmd),
            pw::OkStatus());

  // -------------------------------------------------------------------------
  // Step 4: Derive session keys (this happens on both PCD and tag)
  // -------------------------------------------------------------------------
  std::array<std::byte, 16> ses_auth_enc_key{};
  std::array<std::byte, 16> ses_auth_mac_key{};
  ASSERT_EQ(DeriveSessionKeys(kAuthKey, kRndA, kRndB,
                              ses_auth_enc_key, ses_auth_mac_key),
            pw::OkStatus());

  // Log computed session key for debugging
  printf("Computed SesAuthEncKey: ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(ses_auth_enc_key[i]));
  }
  printf("\n");

  printf("Expected SesAuthEncKey: ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(kExpectedSesAuthEncKey[i]));
  }
  printf("\n");

  EXPECT_EQ(std::memcmp(ses_auth_enc_key.data(),
                        kExpectedSesAuthEncKey.data(), 16), 0)
      << "Step 4 FAILED: SesAuthEncKey derivation mismatch - CMAC bug?";

  EXPECT_EQ(std::memcmp(ses_auth_mac_key.data(),
                        kExpectedSesAuthMacKey.data(), 16), 0)
      << "Step 4 FAILED: SesAuthMacKey derivation mismatch";

  // -------------------------------------------------------------------------
  // Step 5: Tag sends encrypted response: TI || RndA' || PDCap2.1 || PCDCap2.2
  // -------------------------------------------------------------------------
  // The tag encrypts with SesAuthEncKey, not AuthKey!
  // RndA' = RndA rotated left by 1 byte

  // Compute RndA' (what the tag should send back)
  std::array<std::byte, 16> expected_rnd_a_prime{};
  RotateLeft1(kRndA, expected_rnd_a_prime);

  printf("Expected RndA' (rotated): ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(expected_rnd_a_prime[i]));
  }
  printf("\n");

  // The tag's response is: TI(4) || RndA'(16) || PDCap2.1(6) || PCDCap2.2(6) = 32 bytes
  // We'll use dummy TI and caps for simulation
  std::array<std::byte, 32> tag_response_plaintext{};
  // TI (4 bytes) - arbitrary for test
  tag_response_plaintext[0] = std::byte{0xA8};
  tag_response_plaintext[1] = std::byte{0x9B};
  tag_response_plaintext[2] = std::byte{0x4E};
  tag_response_plaintext[3] = std::byte{0xF0};
  // RndA' (16 bytes)
  std::copy(expected_rnd_a_prime.begin(), expected_rnd_a_prime.end(),
            tag_response_plaintext.begin() + 4);
  // PDCap2.1 and PCDCap2.2 (12 bytes) - zeros for test
  std::fill(tag_response_plaintext.begin() + 20, tag_response_plaintext.end(),
            std::byte{0x00});

  // Tag encrypts this with SesAuthEncKey
  std::array<std::byte, 32> tag_response_encrypted{};
  ASSERT_EQ(AesCbcEncrypt(ses_auth_enc_key, kZeroIv, tag_response_plaintext,
                          tag_response_encrypted),
            pw::OkStatus());

  printf("Simulated tag encrypted response: ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(tag_response_encrypted[i]));
  }
  printf("...\n");

  // -------------------------------------------------------------------------
  // Step 6: PCD decrypts tag response and verifies RndA'
  // -------------------------------------------------------------------------
  std::array<std::byte, 32> decrypted_response{};
  ASSERT_EQ(AesCbcDecrypt(ses_auth_enc_key, kZeroIv, tag_response_encrypted,
                          decrypted_response),
            pw::OkStatus());

  printf("Decrypted response: ");
  for (size_t i = 0; i < 20; i++) {
    printf("%02X ", static_cast<unsigned>(decrypted_response[i]));
  }
  printf("...\n");

  // Extract RndA' from decrypted response (bytes 4-19)
  pw::ConstByteSpan decrypted_rnd_a_prime(decrypted_response.data() + 4, 16);

  printf("Decrypted RndA': ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(decrypted_rnd_a_prime[i]));
  }
  printf("\n");

  // Verify RndA'
  EXPECT_TRUE(VerifyRndAPrime(kRndA, decrypted_rnd_a_prime))
      << "Step 6 FAILED: RndA' verification failed";
}

// ============================================================================
// Debug Test: Actual values from failing authentication (Run 2)
// ============================================================================

TEST(Ntag424CryptoTest, DebugRealAuthenticationValues_Run2) {
  // Values from latest device log:
  constexpr auto kActualRndA = pw::bytes::Array<
      0xA1, 0x60, 0xB6, 0x1F, 0x96, 0x12, 0x08, 0x41,
      0x6E, 0xE4, 0x22, 0xF5, 0xF1, 0x75, 0xA9, 0x8D>();

  constexpr auto kActualRndB = pw::bytes::Array<
      0x8D, 0xB4, 0xF9, 0x91, 0xEB, 0x0D, 0xE0, 0xA7,
      0xA8, 0x8C, 0xC6, 0x2F, 0x66, 0x8C, 0xC0, 0xAB>();

  constexpr auto kZeroAuthKey = pw::bytes::Array<
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();

  // Device-computed session key
  constexpr auto kDeviceSesAuthEncKey = pw::bytes::Array<
      0xFF, 0xB1, 0x8D, 0x1B, 0x79, 0x61, 0xE4, 0xE8,
      0x81, 0x48, 0x60, 0x0E, 0x69, 0xCE, 0xC0, 0x13>();

  // Encrypted response from tag
  constexpr auto kEncryptedResponse = pw::bytes::Array<
      0x52, 0x12, 0xD8, 0xF9, 0x4B, 0xF1, 0x95, 0x76,
      0xC3, 0x71, 0x24, 0x69, 0x5B, 0xEF, 0xA2, 0x8B,
      0xE0, 0x5A, 0x97, 0x40, 0x44, 0x2C, 0x15, 0x80,
      0x65, 0x91, 0xD8, 0xC6, 0xE4, 0xCB, 0x61, 0x2F>();

  // Step 1: Compute session key on host
  std::array<std::byte, 16> host_ses_auth_enc_key{};
  std::array<std::byte, 16> host_ses_auth_mac_key{};
  ASSERT_EQ(DeriveSessionKeys(kZeroAuthKey, kActualRndA, kActualRndB,
                              host_ses_auth_enc_key, host_ses_auth_mac_key),
            pw::OkStatus());

  printf("Host-computed SesAuthEncKey:   ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(host_ses_auth_enc_key[i]));
  }
  printf("\n");

  printf("Device-computed SesAuthEncKey: ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(kDeviceSesAuthEncKey[i]));
  }
  printf("\n");

  // Check if host and device session keys match
  bool keys_match = std::memcmp(host_ses_auth_enc_key.data(),
                                 kDeviceSesAuthEncKey.data(), 16) == 0;
  printf("Session keys match: %s\n", keys_match ? "YES" : "NO");

  if (!keys_match) {
    printf("ERROR: Host and device compute different session keys!\n");
    printf("This indicates a bug in device CMAC implementation.\n");
  }

  // Step 2: Try decrypting with BOTH keys to see what we get
  constexpr auto kZeroIv = pw::bytes::Array<
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();

  std::array<std::byte, 32> decrypted_with_host_key{};
  ASSERT_EQ(AesCbcDecrypt(host_ses_auth_enc_key, kZeroIv, kEncryptedResponse,
                          decrypted_with_host_key),
            pw::OkStatus());

  printf("\nDecrypted with HOST key:\n");
  printf("  TI:    %02X %02X %02X %02X\n",
         static_cast<unsigned>(decrypted_with_host_key[0]),
         static_cast<unsigned>(decrypted_with_host_key[1]),
         static_cast<unsigned>(decrypted_with_host_key[2]),
         static_cast<unsigned>(decrypted_with_host_key[3]));
  printf("  RndA': ");
  for (size_t i = 4; i < 20; i++) {
    printf("%02X ", static_cast<unsigned>(decrypted_with_host_key[i]));
  }
  printf("\n");

  // Expected RndA' (RndA rotated left by 1 byte)
  printf("  Expected RndA': ");
  for (size_t i = 1; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(kActualRndA[i]));
  }
  printf("%02X \n", static_cast<unsigned>(kActualRndA[0]));

  // Check if RndA' matches
  bool rnda_matches = true;
  for (size_t i = 0; i < 15; i++) {
    if (decrypted_with_host_key[4 + i] != kActualRndA[i + 1]) {
      rnda_matches = false;
      break;
    }
  }
  if (decrypted_with_host_key[19] != kActualRndA[0]) {
    rnda_matches = false;
  }
  printf("  RndA' matches expected: %s\n", rnda_matches ? "YES" : "NO");

  // This tells us whether the tag uses the same session key derivation
  if (rnda_matches) {
    printf("\nSUCCESS: Tag uses same session key derivation as AN12196!\n");
  } else {
    printf("\nFAILURE: Tag produces different RndA' - session key mismatch.\n");
    printf("Possible causes:\n");
    printf("  1. Tag uses different session key derivation (e.g., LRP mode)\n");
    printf("  2. Tag hardware v3.0 has different algorithm\n");
    printf("  3. Data corruption in NFC communication\n");
  }
}

// ============================================================================
// Debug Test: Actual values from failing authentication (Run 1)
// ============================================================================
// These values were captured from a real authentication attempt that failed.
// Use this to verify host computation matches what the device should compute.

TEST(Ntag424CryptoTest, DebugRealAuthenticationValues) {
  // Actual values from device log:
  constexpr auto kActualRndA = pw::bytes::Array<
      0x1D, 0x37, 0x55, 0xA0, 0xFA, 0xB9, 0x07, 0x69,
      0xF0, 0x69, 0xAE, 0x73, 0x69, 0x37, 0x5B, 0x59>();

  constexpr auto kActualRndB = pw::bytes::Array<
      0xD1, 0x1E, 0x81, 0x45, 0x81, 0xEB, 0xCB, 0x63,
      0x6B, 0xA9, 0xE8, 0x78, 0x31, 0x1A, 0x86, 0xAA>();

  constexpr auto kZeroAuthKey = pw::bytes::Array<
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>();

  // Expected SV1 from device log (verified manually):
  constexpr auto kExpectedSV1 = pw::bytes::Array<
      0xA5, 0x5A, 0x00, 0x01, 0x00, 0x80, 0x1D, 0x37,
      0x84, 0xBE, 0x7B, 0xFC, 0x86, 0x82, 0xCB, 0x63,
      0x6B, 0xA9, 0xE8, 0x78, 0x31, 0x1A, 0x86, 0xAA,
      0xF0, 0x69, 0xAE, 0x73, 0x69, 0x37, 0x5B, 0x59>();

  // Step 1: Verify SV1 calculation
  std::array<std::byte, 32> computed_sv1{};
  CalculateSV1(kActualRndA, kActualRndB, computed_sv1);

  printf("Expected SV1: ");
  for (size_t i = 0; i < 32; i++) {
    printf("%02X ", static_cast<unsigned>(kExpectedSV1[i]));
  }
  printf("\n");

  printf("Computed SV1: ");
  for (size_t i = 0; i < 32; i++) {
    printf("%02X ", static_cast<unsigned>(computed_sv1[i]));
  }
  printf("\n");

  EXPECT_EQ(std::memcmp(computed_sv1.data(), kExpectedSV1.data(), 32), 0)
      << "SV1 calculation mismatch";

  // Step 2: Derive session keys
  std::array<std::byte, 16> ses_auth_enc_key{};
  std::array<std::byte, 16> ses_auth_mac_key{};
  ASSERT_EQ(DeriveSessionKeys(kZeroAuthKey, kActualRndA, kActualRndB,
                              ses_auth_enc_key, ses_auth_mac_key),
            pw::OkStatus());

  printf("Host-computed SesAuthEncKey: ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(ses_auth_enc_key[i]));
  }
  printf("\n");

  // Device log showed: SesAuthEncKey=28 F6 98 15 FC 41 3F 27...
  // If host produces the same value, the algorithm is consistent.
  // If host produces different value, there's a bug in our formula.
  printf("Device reported: 28 F6 98 15 FC 41 3F 27...\n");

  // Step 3: Verify RndB' calculation
  std::array<std::byte, 16> rnd_b_prime{};
  RotateLeft1(kActualRndB, rnd_b_prime);

  // Expected from log: Part2 plaintext[16:31] = 1E 81 45 81 EB CB 63 6B A9 E8 78 31 1A 86 AA D1
  constexpr auto kExpectedRndBPrime = pw::bytes::Array<
      0x1E, 0x81, 0x45, 0x81, 0xEB, 0xCB, 0x63, 0x6B,
      0xA9, 0xE8, 0x78, 0x31, 0x1A, 0x86, 0xAA, 0xD1>();

  printf("Expected RndB': ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(kExpectedRndBPrime[i]));
  }
  printf("\n");

  printf("Computed RndB': ");
  for (size_t i = 0; i < 16; i++) {
    printf("%02X ", static_cast<unsigned>(rnd_b_prime[i]));
  }
  printf("\n");

  EXPECT_EQ(std::memcmp(rnd_b_prime.data(), kExpectedRndBPrime.data(), 16), 0)
      << "RndB' calculation mismatch";
}

}  // namespace
}  // namespace maco::nfc
