// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class AuthenticateNewSessionResponse implements flatbuffers.IUnpackableObject<AuthenticateNewSessionResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AuthenticateNewSessionResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAuthenticateNewSessionResponse(bb:flatbuffers.ByteBuffer, obj?:AuthenticateNewSessionResponse):AuthenticateNewSessionResponse {
  return (obj || new AuthenticateNewSessionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAuthenticateNewSessionResponse(bb:flatbuffers.ByteBuffer, obj?:AuthenticateNewSessionResponse):AuthenticateNewSessionResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AuthenticateNewSessionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():string|null
sessionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sessionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

cloudChallenge(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

cloudChallengeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

cloudChallengeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startAuthenticateNewSessionResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sessionIdOffset, 0);
}

static addCloudChallenge(builder:flatbuffers.Builder, cloudChallengeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, cloudChallengeOffset, 0);
}

static createCloudChallengeVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCloudChallengeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endAuthenticateNewSessionResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAuthenticateNewSessionResponse(builder:flatbuffers.Builder, sessionIdOffset:flatbuffers.Offset, cloudChallengeOffset:flatbuffers.Offset):flatbuffers.Offset {
  AuthenticateNewSessionResponse.startAuthenticateNewSessionResponse(builder);
  AuthenticateNewSessionResponse.addSessionId(builder, sessionIdOffset);
  AuthenticateNewSessionResponse.addCloudChallenge(builder, cloudChallengeOffset);
  return AuthenticateNewSessionResponse.endAuthenticateNewSessionResponse(builder);
}

serialize():Uint8Array {
  return this.bb!.bytes();
}

static deserialize(buffer: Uint8Array):AuthenticateNewSessionResponse {
  return AuthenticateNewSessionResponse.getRootAsAuthenticateNewSessionResponse(new flatbuffers.ByteBuffer(buffer))
}

unpack(): AuthenticateNewSessionResponseT {
  return new AuthenticateNewSessionResponseT(
    this.sessionId(),
    this.bb!.createScalarList<number>(this.cloudChallenge.bind(this), this.cloudChallengeLength())
  );
}


unpackTo(_o: AuthenticateNewSessionResponseT): void {
  _o.sessionId = this.sessionId();
  _o.cloudChallenge = this.bb!.createScalarList<number>(this.cloudChallenge.bind(this), this.cloudChallengeLength());
}
}

export class AuthenticateNewSessionResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public sessionId: string|Uint8Array|null = null,
  public cloudChallenge: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const sessionId = (this.sessionId !== null ? builder.createString(this.sessionId!) : 0);
  const cloudChallenge = AuthenticateNewSessionResponse.createCloudChallengeVector(builder, this.cloudChallenge);

  return AuthenticateNewSessionResponse.createAuthenticateNewSessionResponse(builder,
    sessionId,
    cloudChallenge
  );
}
}
