// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ReasonCheckInOtherMachine, ReasonCheckInOtherMachineT } from '../fbs/reason-check-in-other-machine';
import { ReasonCheckInOtherTag, ReasonCheckInOtherTagT } from '../fbs/reason-check-in-other-tag';
import { ReasonSelfCheckout, ReasonSelfCheckoutT } from '../fbs/reason-self-checkout';
import { ReasonTimeout, ReasonTimeoutT } from '../fbs/reason-timeout';
import { ReasonUi, ReasonUiT } from '../fbs/reason-ui';


export enum CheckOutReason {
  NONE = 0,
  ui = 1,
  other_tag = 2,
  other_machine = 3,
  timeout = 4,
  self_checkout = 5
}

export function unionToCheckOutReason(
  type: CheckOutReason,
  accessor: (obj:ReasonCheckInOtherMachine|ReasonCheckInOtherTag|ReasonSelfCheckout|ReasonTimeout|ReasonUi) => ReasonCheckInOtherMachine|ReasonCheckInOtherTag|ReasonSelfCheckout|ReasonTimeout|ReasonUi|null
): ReasonCheckInOtherMachine|ReasonCheckInOtherTag|ReasonSelfCheckout|ReasonTimeout|ReasonUi|null {
  switch(CheckOutReason[type]) {
    case 'NONE': return null; 
    case 'ui': return accessor(new ReasonUi())! as ReasonUi;
    case 'other_tag': return accessor(new ReasonCheckInOtherTag())! as ReasonCheckInOtherTag;
    case 'other_machine': return accessor(new ReasonCheckInOtherMachine())! as ReasonCheckInOtherMachine;
    case 'timeout': return accessor(new ReasonTimeout())! as ReasonTimeout;
    case 'self_checkout': return accessor(new ReasonSelfCheckout())! as ReasonSelfCheckout;
    default: return null;
  }
}

export function unionListToCheckOutReason(
  type: CheckOutReason, 
  accessor: (index: number, obj:ReasonCheckInOtherMachine|ReasonCheckInOtherTag|ReasonSelfCheckout|ReasonTimeout|ReasonUi) => ReasonCheckInOtherMachine|ReasonCheckInOtherTag|ReasonSelfCheckout|ReasonTimeout|ReasonUi|null, 
  index: number
): ReasonCheckInOtherMachine|ReasonCheckInOtherTag|ReasonSelfCheckout|ReasonTimeout|ReasonUi|null {
  switch(CheckOutReason[type]) {
    case 'NONE': return null; 
    case 'ui': return accessor(index, new ReasonUi())! as ReasonUi;
    case 'other_tag': return accessor(index, new ReasonCheckInOtherTag())! as ReasonCheckInOtherTag;
    case 'other_machine': return accessor(index, new ReasonCheckInOtherMachine())! as ReasonCheckInOtherMachine;
    case 'timeout': return accessor(index, new ReasonTimeout())! as ReasonTimeout;
    case 'self_checkout': return accessor(index, new ReasonSelfCheckout())! as ReasonSelfCheckout;
    default: return null;
  }
}
