// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MachineUsage, MachineUsageT } from '../fbs/machine-usage.js';


export class MachineUsageHistory implements flatbuffers.IUnpackableObject<MachineUsageHistoryT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MachineUsageHistory {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMachineUsageHistory(bb:flatbuffers.ByteBuffer, obj?:MachineUsageHistory):MachineUsageHistory {
  return (obj || new MachineUsageHistory()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMachineUsageHistory(bb:flatbuffers.ByteBuffer, obj?:MachineUsageHistory):MachineUsageHistory {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MachineUsageHistory()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

records(index: number, obj?:MachineUsage):MachineUsage|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MachineUsage()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

recordsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMachineUsageHistory(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRecords(builder:flatbuffers.Builder, recordsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, recordsOffset, 0);
}

static createRecordsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRecordsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMachineUsageHistory(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMachineUsageHistory(builder:flatbuffers.Builder, recordsOffset:flatbuffers.Offset):flatbuffers.Offset {
  MachineUsageHistory.startMachineUsageHistory(builder);
  MachineUsageHistory.addRecords(builder, recordsOffset);
  return MachineUsageHistory.endMachineUsageHistory(builder);
}

unpack(): MachineUsageHistoryT {
  return new MachineUsageHistoryT(
    this.bb!.createObjList<MachineUsage, MachineUsageT>(this.records.bind(this), this.recordsLength())
  );
}


unpackTo(_o: MachineUsageHistoryT): void {
  _o.records = this.bb!.createObjList<MachineUsage, MachineUsageT>(this.records.bind(this), this.recordsLength());
}
}

export class MachineUsageHistoryT implements flatbuffers.IGeneratedObject {
constructor(
  public records: (MachineUsageT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const records = MachineUsageHistory.createRecordsVector(builder, builder.createObjectOffsetList(this.records));

  return MachineUsageHistory.createMachineUsageHistory(builder,
    records
  );
}
}
