// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ReasonUi implements flatbuffers.IUnpackableObject<ReasonUiT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReasonUi {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReasonUi(bb:flatbuffers.ByteBuffer, obj?:ReasonUi):ReasonUi {
  return (obj || new ReasonUi()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReasonUi(bb:flatbuffers.ByteBuffer, obj?:ReasonUi):ReasonUi {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReasonUi()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startReasonUi(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endReasonUi(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReasonUi(builder:flatbuffers.Builder):flatbuffers.Offset {
  ReasonUi.startReasonUi(builder);
  return ReasonUi.endReasonUi(builder);
}

unpack(): ReasonUiT {
  return new ReasonUiT();
}


unpackTo(_o: ReasonUiT): void {}
}

export class ReasonUiT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ReasonUi.createReasonUi(builder);
}
}
