// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AuthRequired, AuthRequiredT } from '../fbs/auth-required.js';
import { Rejected, RejectedT } from '../fbs/rejected.js';
import { StartSessionResult, unionToStartSessionResult, unionListToStartSessionResult } from '../fbs/start-session-result.js';
import { TokenSession, TokenSessionT } from '../fbs/token-session.js';


export class StartSessionResponse implements flatbuffers.IUnpackableObject<StartSessionResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StartSessionResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStartSessionResponse(bb:flatbuffers.ByteBuffer, obj?:StartSessionResponse):StartSessionResponse {
  return (obj || new StartSessionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStartSessionResponse(bb:flatbuffers.ByteBuffer, obj?:StartSessionResponse):StartSessionResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StartSessionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

resultType():StartSessionResult {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StartSessionResult.NONE;
}

result<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startStartSessionResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addResultType(builder:flatbuffers.Builder, resultType:StartSessionResult) {
  builder.addFieldInt8(0, resultType, StartSessionResult.NONE);
}

static addResult(builder:flatbuffers.Builder, resultOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, resultOffset, 0);
}

static endStartSessionResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStartSessionResponse(builder:flatbuffers.Builder, resultType:StartSessionResult, resultOffset:flatbuffers.Offset):flatbuffers.Offset {
  StartSessionResponse.startStartSessionResponse(builder);
  StartSessionResponse.addResultType(builder, resultType);
  StartSessionResponse.addResult(builder, resultOffset);
  return StartSessionResponse.endStartSessionResponse(builder);
}

serialize():Uint8Array {
  return this.bb!.bytes();
}

static deserialize(buffer: Uint8Array):StartSessionResponse {
  return StartSessionResponse.getRootAsStartSessionResponse(new flatbuffers.ByteBuffer(buffer))
}

unpack(): StartSessionResponseT {
  return new StartSessionResponseT(
    this.resultType(),
    (() => {
      const temp = unionToStartSessionResult(this.resultType(), this.result.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: StartSessionResponseT): void {
  _o.resultType = this.resultType();
  _o.result = (() => {
      const temp = unionToStartSessionResult(this.resultType(), this.result.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class StartSessionResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public resultType: StartSessionResult = StartSessionResult.NONE,
  public result: AuthRequiredT|RejectedT|TokenSessionT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const result = builder.createObjectOffset(this.result);

  return StartSessionResponse.createStartSessionResponse(builder,
    this.resultType,
    result
  );
}
}
