// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: particle/device_config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FirebaseId } from "../common";

export const protobufPackage = "maco.proto.particle";

/** Hardware revision of the terminal device */
export enum HwRevision {
  HW_REVISION_UNSPECIFIED = 0,
  HW_REVISION_BREADBOARD = 1,
  HW_REVISION_PROTOTYPE = 2,
  UNRECOGNIZED = -1,
}

/** Machine control mechanism */
export interface MachineControl {
  control?: { $case: "relay"; relay: RelayControl } | undefined;
}

/** Relay-based machine control */
export interface RelayControl {
}

/** Machine definition with permissions */
export interface Machine {
  /** Firebase machine ID */
  id:
    | FirebaseId
    | undefined;
  /** Human-readable label */
  label: string;
  /** Firebase permission IDs required to use this machine */
  requiredPermissions: FirebaseId[];
  /** Control mechanism for the machine */
  control: MachineControl | undefined;
}

/** Terminal device configuration stored in Particle Ledger */
export interface DeviceConfig {
  /** Hardware revision of the device */
  hwRevision: HwRevision;
  /** Machines controlled by this terminal */
  machines: Machine[];
  /** Gateway server hostname or IP address */
  gatewayHost: string;
  /** Gateway server port */
  gatewayPort: number;
}

function createBaseMachineControl(): MachineControl {
  return { control: undefined };
}

export const MachineControl: MessageFns<MachineControl> = {
  encode(message: MachineControl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.control?.$case) {
      case "relay":
        RelayControl.encode(message.control.relay, writer.uint32(10).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MachineControl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMachineControl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.control = { $case: "relay", relay: RelayControl.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MachineControl>): MachineControl {
    return MachineControl.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MachineControl>): MachineControl {
    const message = createBaseMachineControl();
    switch (object.control?.$case) {
      case "relay": {
        if (object.control?.relay !== undefined && object.control?.relay !== null) {
          message.control = { $case: "relay", relay: RelayControl.fromPartial(object.control.relay) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseRelayControl(): RelayControl {
  return {};
}

export const RelayControl: MessageFns<RelayControl> = {
  encode(_: RelayControl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelayControl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelayControl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RelayControl>): RelayControl {
    return RelayControl.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<RelayControl>): RelayControl {
    const message = createBaseRelayControl();
    return message;
  },
};

function createBaseMachine(): Machine {
  return { id: undefined, label: "", requiredPermissions: [], control: undefined };
}

export const Machine: MessageFns<Machine> = {
  encode(message: Machine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      FirebaseId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.label !== "") {
      writer.uint32(18).string(message.label);
    }
    for (const v of message.requiredPermissions) {
      FirebaseId.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.control !== undefined) {
      MachineControl.encode(message.control, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Machine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMachine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = FirebaseId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requiredPermissions.push(FirebaseId.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.control = MachineControl.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Machine>): Machine {
    return Machine.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Machine>): Machine {
    const message = createBaseMachine();
    message.id = (object.id !== undefined && object.id !== null) ? FirebaseId.fromPartial(object.id) : undefined;
    message.label = object.label ?? "";
    message.requiredPermissions = object.requiredPermissions?.map((e) => FirebaseId.fromPartial(e)) || [];
    message.control = (object.control !== undefined && object.control !== null)
      ? MachineControl.fromPartial(object.control)
      : undefined;
    return message;
  },
};

function createBaseDeviceConfig(): DeviceConfig {
  return { hwRevision: 0, machines: [], gatewayHost: "", gatewayPort: 0 };
}

export const DeviceConfig: MessageFns<DeviceConfig> = {
  encode(message: DeviceConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hwRevision !== 0) {
      writer.uint32(8).int32(message.hwRevision);
    }
    for (const v of message.machines) {
      Machine.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.gatewayHost !== "") {
      writer.uint32(26).string(message.gatewayHost);
    }
    if (message.gatewayPort !== 0) {
      writer.uint32(32).uint32(message.gatewayPort);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hwRevision = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.machines.push(Machine.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.gatewayHost = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.gatewayPort = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeviceConfig>): DeviceConfig {
    return DeviceConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeviceConfig>): DeviceConfig {
    const message = createBaseDeviceConfig();
    message.hwRevision = object.hwRevision ?? 0;
    message.machines = object.machines?.map((e) => Machine.fromPartial(e)) || [];
    message.gatewayHost = object.gatewayHost ?? "";
    message.gatewayPort = object.gatewayPort ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
