// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

import { test, expect } from "@playwright/test"
import { readFileSync } from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { clearCollections, getCheckoutDocs } from "./helpers"
import { NFC_USER_ID } from "./global-setup"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

/** Read picc+cmac generated by global-setup.ts */
function readE2eData(): { picc: string; cmac: string; authUid: string } {
  const dataPath = path.resolve(__dirname, ".e2e-data.json")
  return JSON.parse(readFileSync(dataPath, "utf-8"))
}

test.beforeEach(async () => {
  await clearCollections("checkouts")
})

test.describe("NFC tag checkout", () => {
  test("tag-identified user — full E2E through Functions emulator", async ({
    page,
  }) => {
    const { picc, cmac } = readE2eData()

    // Navigate with picc+cmac params — hits real Functions emulator
    await page.goto(`/?picc=${picc}&cmac=${cmac}`)

    // ── No landing page — tag identifies the user directly ──
    // Wait for tag verification to complete and person to be pre-filled
    // Name is split into Vorname="NFC" and Nachname="Tester"
    await expect(page.getByText("nfc@test.com")).toBeVisible({
      timeout: 15_000,
    })

    // "Weiter" should be enabled (pre-filled user)
    await expect(
      page.getByRole("button", { name: "Weiter" }),
    ).toBeEnabled()

    // No terms checkbox for pre-filled users
    await expect(page.locator("#terms-accept")).not.toBeVisible()

    // ── Proceed through checkout ──
    await page.getByRole("button", { name: "Weiter" }).click()
    await expect(page.getByText("Werkstätten wählen")).toBeVisible()

    await page.getByRole("button", { name: "Check-Out" }).click()
    await expect(page.getByText("Zusammenfassung")).toBeVisible()

    // Submit
    await page.getByRole("button", { name: "Senden & zur Kasse" }).click()

    // ── Payment result ──
    await expect(page.getByText("Vielen Dank!")).toBeVisible({
      timeout: 10_000,
    })

    // ── Verify Firestore ──
    const checkouts = await getCheckoutDocs()
    expect(checkouts.length).toBeGreaterThanOrEqual(1)

    const checkout = checkouts[0] as Record<string, unknown>
    expect(checkout.status).toBe("closed")

    // userId should reference the NFC user
    const userIdRef = checkout.userId as { path: string }
    expect(userIdRef.path).toBe(`users/${NFC_USER_ID}`)
  })

  test("kiosk mode — shows NFC hint inline with checkout form", async ({ page }) => {
    await page.goto("/?kiosk")

    // Check-in form visible immediately with inline NFC hint
    await expect(page.getByText("Deine Angaben")).toBeVisible()
    await expect(
      page.getByText("Badge an den Leser halten, um deine Daten zu laden"),
    ).toBeVisible()

    // No login hint in kiosk mode
    await expect(page.getByText("Bereits registriert?")).not.toBeVisible()
  })
})
