// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

import { test, expect } from "@playwright/test"
import { FieldValue } from "firebase-admin/firestore"
import { readFileSync } from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { clearCollections, getAdminFirestore, getCheckoutDocs } from "./helpers"
import { NFC_TAG_UID, NFC_TAG_UID_2, NFC_USER_ID } from "./global-setup"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

/** Read picc+cmac generated by global-setup.ts */
function readE2eData(): {
  picc: string
  cmac: string
  picc2: string
  cmac2: string
  authUid: string
} {
  const dataPath = path.resolve(__dirname, ".e2e-data.json")
  return JSON.parse(readFileSync(dataPath, "utf-8"))
}

test.beforeEach(async () => {
  await clearCollections("checkouts")
  // The seeded piccs encode counter=0; the SDM replay defense rejects a
  // second tap with the same counter. Each browser project re-runs the
  // suite, so without this reset the second project trips the defense.
  const db = getAdminFirestore()
  await Promise.all(
    [NFC_TAG_UID, NFC_TAG_UID_2].map((uid) =>
      db
        .collection("tokens")
        .doc(uid)
        .update({ lastSdmCounter: FieldValue.delete() }),
    ),
  )
})

test.describe("NFC tag checkout", () => {
  test("tag-identified user — full E2E through Functions emulator", async ({
    page,
  }) => {
    const { picc, cmac } = readE2eData()

    // Navigate to the wizard's canonical tag entry, /checkin?picc=…&cmac=…
    // (the refactor reserves "/" for typed entries; the kiosk lands on
    // /checkin directly). Going via the "/" dispatcher would verify the tag
    // there AND again in the wizard — the second tap of the same SDM counter
    // trips the replay defense (verify_tag.ts) and falls back to anon check-in.
    await page.goto(`/checkin?picc=${picc}&cmac=${cmac}`)

    // ── No landing page — tag identifies the user directly ──
    // Wait for tag verification to complete and person to be pre-filled
    // Name is split into Vorname="NFC" and Nachname="Tester"
    await expect(page.getByText("nfc@test.com")).toBeVisible({
      timeout: 15_000,
    })

    // "Weiter" should be enabled (pre-filled user)
    await expect(
      page.getByRole("button", { name: "Weiter" }),
    ).toBeEnabled()

    // No terms checkbox for pre-filled users
    await expect(page.locator("#terms-accept")).not.toBeVisible()

    // ── Proceed through checkout ──
    await page.getByRole("button", { name: "Weiter" }).click()
    await expect(page.getByText("Werkstätten wählen")).toBeVisible()

    await page.getByRole("button", { name: "Zum Checkout" }).click()
    await expect(page.getByText("Dein Besuch")).toBeVisible()

    // Submit
    await page.getByRole("button", { name: "Weiter zum Bezahlen" }).click()

    // ── Payment result (Step 4) ──
    await expect(page.getByText("Zu bezahlen")).toBeVisible({
      timeout: 10_000,
    })

    // Issue #414: the seeded NFC user is a Vereinsmitglied, so the
    // Sammelrechnung (monthly-bill) payment tab must be offered even though
    // the tag-tap principal has no client-side user doc. Before the fix the
    // tab was gated on `identifiedUserDoc?.activeMembership` (null for a tag
    // tap) and the member only ever saw QR-Rechnung + TWINT.
    await expect(
      page.getByRole("tab", { name: "Sammelrechnung" }),
    ).toBeVisible()

    // ── Verify Firestore ──
    const checkouts = await getCheckoutDocs()
    expect(checkouts.length).toBeGreaterThanOrEqual(1)

    const checkout = checkouts[0] as Record<string, unknown>
    expect(checkout.status).toBe("closed")

    // userId should reference the NFC user
    const userIdRef = checkout.userId as { path: string }
    expect(userIdRef.path).toBe(`users/${NFC_USER_ID}`)
  })

  test("switching badge re-prefills the new user — no stuck state (#420)", async ({
    page,
  }) => {
    const { picc, cmac, picc2, cmac2 } = readE2eData()

    // First badge: land on the wizard's canonical tag entry. This is exactly
    // what BridgeNfcRouter does for a kiosk tap (navigate to /checkin?picc…).
    await page.goto(`/checkin?picc=${picc}&cmac=${cmac}`)
    await expect(page.getByText("nfc@test.com")).toBeVisible({
      timeout: 15_000,
    })

    // Second badge tapped while the first is already identified. Before the
    // #420 fix the bridge routed through "/" (double-verify), the SDM replay
    // defense rejected the wizard's second verify, and the page got stuck:
    // neither tag- nor anon-identified, no re-prefill. The new identity must
    // now replace the first on the primary card.
    await page.goto(`/checkin?picc=${picc2}&cmac=${cmac2}`)

    // The second user's email replaces the first — the switch took effect.
    await expect(page.getByText("badge2@test.com")).toBeVisible({
      timeout: 15_000,
    })
    await expect(page.getByText("nfc@test.com")).not.toBeVisible()

    // And the wizard is usable, not stuck: the pre-filled user can proceed.
    await expect(
      page.getByRole("button", { name: "Weiter" }),
    ).toBeEnabled()
  })

  // Issue #689: a badge tap over an idle, identified kiosk screen switched
  // principal inside the live page. The wizard's listeners stayed bound to
  // the first member, so the second one saw the first one's family roster.
  // Unlike the #420 test above this drives the tap through a fake Electron
  // bridge — the in-place path `page.goto` never takes.
  test("bridge tap over an identified session reloads — no roster leak (#689)", async ({
    page,
  }) => {
    const { picc, cmac, picc2, cmac2 } = readE2eData()
    const db = getAdminFirestore()
    // A's seeded activeMembership pointer; a co-member sharing it makes the
    // roster readable for A's tag session (shareActiveMembershipActingAs).
    const membershipRef = db.doc("memberships/e2e-nfc-membership")
    const kidRef = db.doc("users/e2e-switch-family-kid")
    await kidRef.set({
      firstName: "Fami",
      lastName: "Kind",
      userType: "kind",
      roles: [],
      permissions: [],
      activeMembership: membershipRef,
    })
    await membershipRef.set({
      type: "family",
      status: "active",
      members: [db.doc(`users/${NFC_USER_ID}`), kidRef],
    })

    try {
      await page.addInitScript(() => {
        const listeners: ((e: { physicalUid: string; url?: string }) => void)[] =
          []
        const w = window as unknown as Record<string, unknown>
        w.__fakeNfcTap = (url: string) =>
          listeners.forEach((cb) => cb({ physicalUid: "fake", url }))
        w.bridge = {
          mode: "kiosk",
          features: ["nfc"],
          bearer: async () => null,
          // The real bridge wipes the Electron partition; counting the call
          // (across the reload) is what this test needs.
          resetSession: async () => {
            const n = Number(sessionStorage.getItem("fakeBridgeResets") ?? 0)
            sessionStorage.setItem("fakeBridgeResets", String(n + 1))
          },
          getUrl: async () => location.href,
          onUrlChange: () => () => {},
          onNfcTag: (cb: (e: { physicalUid: string; url?: string }) => void) => {
            listeners.push(cb)
            return () => {
              const i = listeners.indexOf(cb)
              if (i >= 0) listeners.splice(i, 1)
            }
          },
        }
      })

      await page.goto(`/checkin?kiosk=&picc=${picc}&cmac=${cmac}`)
      await expect(page.getByText("nfc@test.com")).toBeVisible({
        timeout: 15_000,
      })
      await expect(page.getByRole("button", { name: "Fami Kind" })).toBeVisible()

      // B taps without A having started anything — nothing to preserve, so
      // no dialog, but the page must be wiped and reloaded.
      await page.evaluate(
        (url) =>
          (window as unknown as { __fakeNfcTap: (u: string) => void })
            .__fakeNfcTap(url),
        `https://id.example.ch/?picc=${picc2}&cmac=${cmac2}`,
      )

      await expect(page.getByText("badge2@test.com")).toBeVisible({
        timeout: 15_000,
      })
      await expect(page.getByText("nfc@test.com")).not.toBeVisible()
      await expect(
        page.getByRole("button", { name: "Fami Kind" }),
      ).not.toBeVisible()
      await expect(page.getByRole("alertdialog")).not.toBeVisible()
      expect(
        await page.evaluate(() => sessionStorage.getItem("fakeBridgeResets")),
      ).toBe("1")
    } finally {
      await Promise.all([membershipRef.delete(), kidRef.delete()])
    }
  })

  test("kiosk mode — shows NFC hint inline in the account section", async ({ page }) => {
    await page.goto("/?kiosk")

    // The account section is the default for an anonymous kiosk visitor:
    // switcher on top, identifier field, and the animated badge affordance
    // in its hero state below the "oder" divider.
    await expect(page.getByTestId("checkin-seg-account")).toBeVisible()
    await expect(page.getByTestId("checkin-identifier")).toBeVisible()
    await expect(page.getByTestId("nfc-affordance")).toHaveAttribute(
      "data-mode",
      "hero",
    )

    // No Google sign-in at the shared terminal.
    await expect(page.getByText("Mit Google anmelden")).not.toBeVisible()
  })
})
