// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

import { test, expect } from "@playwright/test"
import { FieldValue } from "firebase-admin/firestore"
import { readFileSync } from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { clearCollections, getAdminFirestore, getCheckoutDocs } from "./helpers"
import { NFC_TAG_UID, NFC_TAG_UID_2, NFC_USER_ID } from "./global-setup"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

/** Read picc+cmac generated by global-setup.ts */
function readE2eData(): {
  picc: string
  cmac: string
  picc2: string
  cmac2: string
  authUid: string
} {
  const dataPath = path.resolve(__dirname, ".e2e-data.json")
  return JSON.parse(readFileSync(dataPath, "utf-8"))
}

test.beforeEach(async () => {
  await clearCollections("checkouts")
  // The seeded piccs encode counter=0; the SDM replay defense rejects a
  // second tap with the same counter. Each browser project re-runs the
  // suite, so without this reset the second project trips the defense.
  const db = getAdminFirestore()
  await Promise.all(
    [NFC_TAG_UID, NFC_TAG_UID_2].map((uid) =>
      db
        .collection("tokens")
        .doc(uid)
        .update({ lastSdmCounter: FieldValue.delete() }),
    ),
  )
})

test.describe("NFC tag checkout", () => {
  test("tag-identified user — full E2E through Functions emulator", async ({
    page,
  }) => {
    const { picc, cmac } = readE2eData()

    // Navigate to the wizard's canonical tag entry, /checkin?picc=…&cmac=…
    // (the refactor reserves "/" for typed entries; the kiosk lands on
    // /checkin directly). Going via the "/" dispatcher would verify the tag
    // there AND again in the wizard — the second tap of the same SDM counter
    // trips the replay defense (verify_tag.ts) and falls back to anon check-in.
    await page.goto(`/checkin?picc=${picc}&cmac=${cmac}`)

    // ── No landing page — tag identifies the user directly ──
    // Wait for tag verification to complete and person to be pre-filled
    // Name is split into Vorname="NFC" and Nachname="Tester"
    await expect(page.getByText("nfc@test.com")).toBeVisible({
      timeout: 15_000,
    })

    // "Weiter" should be enabled (pre-filled user)
    await expect(
      page.getByRole("button", { name: "Weiter" }),
    ).toBeEnabled()

    // No terms checkbox for pre-filled users
    await expect(page.locator("#terms-accept")).not.toBeVisible()

    // ── Proceed through checkout ──
    await page.getByRole("button", { name: "Weiter" }).click()
    await expect(page.getByText("Werkstätten wählen")).toBeVisible()

    await page.getByRole("button", { name: "Zum Checkout" }).click()
    await expect(page.getByText("Dein Besuch")).toBeVisible()

    // Submit
    await page.getByRole("button", { name: "Weiter zum Bezahlen" }).click()

    // ── Payment result (Step 4) ──
    await expect(page.getByText("Zu bezahlen")).toBeVisible({
      timeout: 10_000,
    })

    // Issue #414: the seeded NFC user is a Vereinsmitglied, so the
    // Sammelrechnung (monthly-bill) payment tab must be offered even though
    // the tag-tap principal has no client-side user doc. Before the fix the
    // tab was gated on `identifiedUserDoc?.activeMembership` (null for a tag
    // tap) and the member only ever saw QR-Rechnung + TWINT.
    await expect(
      page.getByRole("tab", { name: "Sammelrechnung" }),
    ).toBeVisible()

    // ── Verify Firestore ──
    const checkouts = await getCheckoutDocs()
    expect(checkouts.length).toBeGreaterThanOrEqual(1)

    const checkout = checkouts[0] as Record<string, unknown>
    expect(checkout.status).toBe("closed")

    // userId should reference the NFC user
    const userIdRef = checkout.userId as { path: string }
    expect(userIdRef.path).toBe(`users/${NFC_USER_ID}`)
  })

  test("switching badge re-prefills the new user — no stuck state (#420)", async ({
    page,
  }) => {
    const { picc, cmac, picc2, cmac2 } = readE2eData()

    // First badge: land on the wizard's canonical tag entry. This is exactly
    // what BridgeNfcRouter does for a kiosk tap (navigate to /checkin?picc…).
    await page.goto(`/checkin?picc=${picc}&cmac=${cmac}`)
    await expect(page.getByText("nfc@test.com")).toBeVisible({
      timeout: 15_000,
    })

    // Second badge tapped while the first is already identified. Before the
    // #420 fix the bridge routed through "/" (double-verify), the SDM replay
    // defense rejected the wizard's second verify, and the page got stuck:
    // neither tag- nor anon-identified, no re-prefill. The new identity must
    // now replace the first on the primary card.
    await page.goto(`/checkin?picc=${picc2}&cmac=${cmac2}`)

    // The second user's email replaces the first — the switch took effect.
    await expect(page.getByText("badge2@test.com")).toBeVisible({
      timeout: 15_000,
    })
    await expect(page.getByText("nfc@test.com")).not.toBeVisible()

    // And the wizard is usable, not stuck: the pre-filled user can proceed.
    await expect(
      page.getByRole("button", { name: "Weiter" }),
    ).toBeEnabled()
  })

  test("kiosk mode — shows NFC hint inline with checkout form", async ({ page }) => {
    await page.goto("/?kiosk")

    // Check-in form visible immediately with the animated badge affordance
    // in its hero state (untouched form). Heading role: the affordance's
    // subline also contains the words "Deine Angaben".
    await expect(
      page.getByRole("heading", { name: "Deine Angaben" }),
    ).toBeVisible()
    await expect(page.getByTestId("nfc-affordance")).toHaveAttribute(
      "data-mode",
      "hero",
    )

    // No login hint in kiosk mode
    await expect(page.getByText("Bereits registriert?")).not.toBeVisible()
  })
})
