// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

/**
 * Kiosk step-up (ADR-0041): a badge tap yields a checkout-only session; the
 * member area opens only after an OTP (e-mail or SMS) bound to the account's
 * own contact address elevates it. Code sign-ins are elevated at mint and
 * skip the second code. The kiosk UI works browser-side without
 * window.bridge; the emulator skips the bearer. Bridge-only chrome (the
 * remaining-time chip, "Zurück zum Checkout", the account idle watcher,
 * kiosk-flagged post-purchase routing) is covered by unit tests, not here.
 */

import { test, expect } from "@playwright/test"
import { FieldValue } from "firebase-admin/firestore"
import { readFileSync } from "fs"
import path from "path"
import { fileURLToPath } from "url"
import {
  clearCollections,
  getAdminAuth,
  getAdminFirestore,
  getCheckoutItems,
  waitForLoginCode,
  waitForSmsCode,
} from "./helpers"
import {
  AUTH_USER_EMAIL,
  NFC_TAG_UID,
  NFC_TAG_UID_2,
  NFC_USER_ID_2,
} from "./global-setup"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

/** picc+cmac generated by global-setup.ts (tag 2 = the non-member user). */
function readE2eData(): { picc2: string; cmac2: string } {
  const dataPath = path.resolve(__dirname, ".e2e-data.json")
  return JSON.parse(readFileSync(dataPath, "utf-8"))
}

const BADGE2_EMAIL = "badge2@test.com"
const BADGE2_PHONE = "+41791234528"

test.beforeEach(async () => {
  await clearCollections("checkouts", "loginCodes")
  // The seeded piccs encode counter=0; reset the replay defense per test.
  const db = getAdminFirestore()
  await Promise.all(
    [NFC_TAG_UID, NFC_TAG_UID_2].map((uid) =>
      db
        .collection("tokens")
        .doc(uid)
        .update({ lastSdmCounter: FieldValue.delete() }),
    ),
  )
})

async function tapBadge2(page: import("@playwright/test").Page) {
  const { picc2, cmac2 } = readE2eData()
  await page.goto(`/checkin?kiosk&picc=${picc2}&cmac=${cmac2}`)
  await expect(page.getByTestId("identity-strip")).toBeVisible({
    timeout: 15_000,
  })
  await expect(page.getByTestId("identity-strip")).toContainText("Zweit")
}

test.describe("Kiosk step-up elevation", () => {
  test("badge tap → e-mail code → membership purchase lands in the kiosk cart", async ({
    page,
  }) => {
    await tapBadge2(page)

    // The badge user is not a member: both entry points show.
    await expect(page.getByTestId("kiosk-account-actions")).toBeVisible()
    await page.getByTestId("kiosk-become-member").click()

    // A badge-only session must step up first — the interstitial offers the
    // masked stored e-mail (no phone linked for this user → no SMS button).
    await expect(page.getByTestId("kiosk-elevation-dialog")).toBeVisible()
    await expect(page.getByTestId("kiosk-elevation-email")).toContainText(
      "ba•••@te•••.com",
    )
    await expect(page.getByTestId("kiosk-elevation-sms")).not.toBeVisible()
    await page.getByTestId("kiosk-elevation-email").click()

    const entry = await waitForLoginCode(BADGE2_EMAIL)
    expect(entry, "debugCode should be present in emulator").toBeTruthy()
    await expect(page.getByTestId("checkin-code-dialog")).toBeVisible()
    await page.getByTestId("checkin-code-input").fill(entry!.code)
    await page.getByTestId("checkin-code-submit").click()

    // Elevated: the queued navigation opens the membership page.
    await expect(page).toHaveURL(/\/account\/membership/, { timeout: 10_000 })
    await expect(
      page.getByRole("heading", { name: "Mitglied werden" }),
    ).toBeVisible()

    await page.getByRole("button", { name: /Einzel-Mitgliedschaft/ }).click()

    // purchaseMembership accepted the elevated actsAs caller and appended
    // the SKU to a fresh checkout; the wizard shows the checkout summary.
    await expect(page).toHaveURL(/\/checkout/, { timeout: 10_000 })
    await expect(page.getByText("Mitgliedschaft").first()).toBeVisible()

    const db = getAdminFirestore()
    const checkouts = await db
      .collection("checkouts")
      .where("userId", "==", db.doc(`users/${NFC_USER_ID_2}`))
      .where("status", "==", "open")
      .get()
    expect(checkouts.size).toBe(1)
    const items = await getCheckoutItems(checkouts.docs[0].id)
    expect(items.some((i) => i.variantId === "single")).toBe(true)
  })

  // The header account menu is a second entry point into the same step-up
  // (ADR-0041 §4). Selecting an item closes the Radix dropdown and opens the
  // Radix elevation dialog in the same tick — this checks the two overlays
  // hand over cleanly and the queued navigation still runs.
  test("badge tap → header account menu → step-up → membership page", async ({
    page,
  }) => {
    await tapBadge2(page)

    const trigger = page.getByRole("button", { name: "Konto-Menü" })
    await expect(trigger).toBeVisible()
    await trigger.click()
    await page.getByRole("menuitem", { name: "Mitgliedschaft" }).click()

    await expect(page.getByRole("menu")).not.toBeVisible()
    await expect(page.getByTestId("kiosk-elevation-dialog")).toBeVisible()
    await page.getByTestId("kiosk-elevation-email").click()

    const entry = await waitForLoginCode(BADGE2_EMAIL)
    expect(entry, "debugCode should be present in emulator").toBeTruthy()
    await expect(page.getByTestId("checkin-code-dialog")).toBeVisible()
    await page.getByTestId("checkin-code-input").fill(entry!.code)
    await page.getByTestId("checkin-code-submit").click()

    await expect(page).toHaveURL(/\/account\/membership/, { timeout: 10_000 })
    await expect(
      page.getByRole("heading", { name: "Mitgliedschaft", level: 1 }),
    ).toBeVisible()
    // No overlay may linger from the dropdown/dialog handover: Radix restores
    // body pointer events once the last modal layer unmounts.
    await expect
      .poll(() => page.evaluate(() => getComputedStyle(document.body).pointerEvents))
      .not.toBe("none")
    await expect(page.getByRole("menu")).toHaveCount(0)
    await expect(page.getByRole("dialog")).toHaveCount(0)
  })

  test("badge tap → SMS code (linked phone) → account area", async ({
    page,
  }) => {
    // Link a phone to the badge user's Auth account (verified self-service
    // state, ADR-0031) — the step-up then offers SMS first.
    const auth = await getAdminAuth()
    try {
      await auth.updateUser(NFC_USER_ID_2, { phoneNumber: BADGE2_PHONE })
    } catch {
      await auth.createUser({
        uid: NFC_USER_ID_2,
        email: BADGE2_EMAIL,
        phoneNumber: BADGE2_PHONE,
      })
    }
    try {
      await tapBadge2(page)
      await page.getByTestId("kiosk-manage-account").click()

      await expect(page.getByTestId("kiosk-elevation-dialog")).toBeVisible()
      await expect(page.getByTestId("kiosk-elevation-sms")).toContainText(
        "+41 79 ••• •• 28",
      )
      await page.getByTestId("kiosk-elevation-sms").click()

      const code = await waitForSmsCode(BADGE2_PHONE)
      expect(code, "SMS code should be present in the Auth emulator").toBeTruthy()
      await expect(page.getByTestId("checkin-code-dialog")).toBeVisible()
      await page.getByTestId("checkin-code-input").fill(code!)
      await page.getByTestId("checkin-code-submit").click()

      await expect(page).toHaveURL(/\/account\/usage/, { timeout: 10_000 })
    } finally {
      // Leave the shared seed as the other specs expect it.
      await auth.updateUser(NFC_USER_ID_2, { phoneNumber: null }).catch(() => {})
    }
  })

  test("a kiosk e-mail-code sign-in is elevated at mint — no second code", async ({
    page,
  }) => {
    await page.goto("/checkin?kiosk")
    await page.getByTestId("checkin-identifier").fill(AUTH_USER_EMAIL)
    await page.getByTestId("checkin-identifier-submit").click()
    const entry = await waitForLoginCode(AUTH_USER_EMAIL)
    await page.getByTestId("checkin-code-input").fill(entry!.code)
    await page.getByTestId("checkin-code-submit").click()
    await expect(page.getByTestId("identity-strip")).toBeVisible({
      timeout: 10_000,
    })

    await page.getByTestId("kiosk-manage-account").click()
    await expect(page.getByTestId("kiosk-elevation-dialog")).not.toBeVisible()
    await expect(page).toHaveURL(/\/account\/usage/, { timeout: 10_000 })

    // Back to the checkout (client-side, as the sidebar link does) keeps the
    // kiosk session: no mount-time sign-out for a `tag:` principal.
    await page.evaluate(() => {
      window.history.pushState({}, "", "/checkin?kiosk")
      window.dispatchEvent(new PopStateEvent("popstate"))
    })
    await expect(page.getByTestId("identity-strip")).toBeVisible({
      timeout: 10_000,
    })
  })

  test("a plain badge session typing /account is bounced to the kiosk check-in", async ({
    page,
  }) => {
    await tapBadge2(page)
    // Client-side navigation: a full page load would drop the in-memory
    // kiosk session altogether (that path lands on /login, not here).
    await page.evaluate(() => {
      window.history.pushState({}, "", "/account/usage")
      window.dispatchEvent(new PopStateEvent("popstate"))
    })
    await expect(page).toHaveURL(/\/checkin\?kiosk/, { timeout: 10_000 })
    await expect(page.getByTestId("identity-strip")).toBeVisible()
  })
})
