// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class MachineControlRelais implements flatbuffers.IUnpackableObject<MachineControlRelaisT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MachineControlRelais {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMachineControlRelais(bb:flatbuffers.ByteBuffer, obj?:MachineControlRelais):MachineControlRelais {
  return (obj || new MachineControlRelais()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMachineControlRelais(bb:flatbuffers.ByteBuffer, obj?:MachineControlRelais):MachineControlRelais {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MachineControlRelais()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startMachineControlRelais(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endMachineControlRelais(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMachineControlRelais(builder:flatbuffers.Builder):flatbuffers.Offset {
  MachineControlRelais.startMachineControlRelais(builder);
  return MachineControlRelais.endMachineControlRelais(builder);
}

unpack(): MachineControlRelaisT {
  return new MachineControlRelaisT();
}


unpackTo(_o: MachineControlRelaisT): void {}
}

export class MachineControlRelaisT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return MachineControlRelais.createMachineControlRelais(builder);
}
}
