// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Key } from './ntag/key.js';
export { KeyBytes, KeyBytesT } from './ntag/key-bytes.js';
export { TagUid, TagUidT } from './ntag/tag-uid.js';
