// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ReasonSelfCheckout implements flatbuffers.IUnpackableObject<ReasonSelfCheckoutT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReasonSelfCheckout {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReasonSelfCheckout(bb:flatbuffers.ByteBuffer, obj?:ReasonSelfCheckout):ReasonSelfCheckout {
  return (obj || new ReasonSelfCheckout()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReasonSelfCheckout(bb:flatbuffers.ByteBuffer, obj?:ReasonSelfCheckout):ReasonSelfCheckout {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReasonSelfCheckout()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startReasonSelfCheckout(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endReasonSelfCheckout(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReasonSelfCheckout(builder:flatbuffers.Builder):flatbuffers.Offset {
  ReasonSelfCheckout.startReasonSelfCheckout(builder);
  return ReasonSelfCheckout.endReasonSelfCheckout(builder);
}

unpack(): ReasonSelfCheckoutT {
  return new ReasonSelfCheckoutT();
}


unpackTo(_o: ReasonSelfCheckoutT): void {}
}

export class ReasonSelfCheckoutT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ReasonSelfCheckout.createReasonSelfCheckout(builder);
}
}
