// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Key {
  Application = 0,
  Terminal = 1,
  Authorization = 2,
  Reserved1 = 3,
  Reserved2 = 4
}
