// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "maco.proto";

/** NTAG424 key slot identifiers */
export enum Key {
  KEY_UNSPECIFIED = 0,
  KEY_APPLICATION = 1,
  KEY_TERMINAL = 2,
  KEY_AUTHORIZATION = 3,
  KEY_RESERVED1 = 4,
  KEY_RESERVED2 = 5,
  UNRECOGNIZED = -1,
}

/** 7-byte NFC tag unique identifier */
export interface TagUid {
  value: Uint8Array;
}

/**
 * Firebase document ID (20 alphanumeric characters)
 * Used for session IDs, user IDs, machine IDs, permission IDs, etc.
 */
export interface FirebaseId {
  value: string;
}

/** 16-byte AES-128 key */
export interface KeyBytes {
  value: Uint8Array;
}

function createBaseTagUid(): TagUid {
  return { value: new Uint8Array(0) };
}

export const TagUid: MessageFns<TagUid> = {
  encode(message: TagUid, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value.length !== 0) {
      writer.uint32(10).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TagUid {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTagUid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<TagUid>): TagUid {
    return TagUid.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TagUid>): TagUid {
    const message = createBaseTagUid();
    message.value = object.value ?? new Uint8Array(0);
    return message;
  },
};

function createBaseFirebaseId(): FirebaseId {
  return { value: "" };
}

export const FirebaseId: MessageFns<FirebaseId> = {
  encode(message: FirebaseId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FirebaseId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFirebaseId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FirebaseId>): FirebaseId {
    return FirebaseId.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FirebaseId>): FirebaseId {
    const message = createBaseFirebaseId();
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseKeyBytes(): KeyBytes {
  return { value: new Uint8Array(0) };
}

export const KeyBytes: MessageFns<KeyBytes> = {
  encode(message: KeyBytes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value.length !== 0) {
      writer.uint32(10).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyBytes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyBytes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<KeyBytes>): KeyBytes {
    return KeyBytes.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<KeyBytes>): KeyBytes {
    const message = createBaseKeyBytes();
    message.value = object.value ?? new Uint8Array(0);
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
