// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

/**
 * Build and deploy the MACO gateway to a Raspberry Pi.
 *
 * Steps:
 *   1. Build the gateway tarball via Bazel (in the gateway repo)
 *   2. Generate .env from config.jsonc + Google Cloud Secret Manager
 *   3. SCP both to the target host and extract
 *
 * Usage:
 *   npx tsx scripts/deploy-gateway.ts --host pi@rpi.local
 *   npx tsx scripts/deploy-gateway.ts --host pi@rpi.local --remote-dir /opt/gateway
 *   npx tsx scripts/deploy-gateway.ts --build-only   # just build, no deploy
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";
import { parseArgs } from "util";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const configDir =
  process.env.OPERATIONS_CONFIG_DIR ||
  resolve(projectRoot, "..", "machine-auth-operations");

// --- Config helpers (same as generate-env.ts) ---

function parseJsonc(text: string): Record<string, unknown> {
  let result = "";
  let i = 0;
  while (i < text.length) {
    if (text[i] === '"') {
      const start = i;
      i++;
      while (i < text.length && text[i] !== '"') {
        if (text[i] === "\\") i++;
        i++;
      }
      i++;
      result += text.slice(start, i);
    } else if (text[i] === "/" && text[i + 1] === "/") {
      while (i < text.length && text[i] !== "\n") i++;
    } else if (text[i] === "/" && text[i + 1] === "*") {
      i += 2;
      while (i < text.length - 1 && !(text[i] === "*" && text[i + 1] === "/")) i++;
      i += 2;
    } else {
      result += text[i];
      i++;
    }
  }
  return JSON.parse(result);
}

function resolveValue(config: Record<string, unknown>, jsonPath: string): string {
  const parts = jsonPath.split(".");
  let current: unknown = config;
  for (const part of parts) {
    if (current == null || typeof current !== "object") return "";
    current = (current as Record<string, unknown>)[part];
  }
  if (current == null) return "";
  return String(current);
}

// --- Secret Manager ---

function fetchSecret(secretName: string): string {
  console.log(`  Fetching secret: ${secretName}`);
  try {
    return execSync(
      `gcloud secrets versions access latest --secret=${secretName}`,
      { encoding: "utf-8" },
    ).trim();
  } catch {
    console.error(`Failed to fetch secret "${secretName}". Check: gcloud config get-value project`);
    process.exit(1);
  }
}

// --- Build ---

function buildTar(): string {
  console.log("\n=== Building gateway tarball ===\n");
  execSync("bazelisk build //maco_gateway:gateway_tar", {
    cwd: projectRoot,
    stdio: "inherit",
  });

  const bazelBin = execSync("bazelisk info bazel-bin", {
    cwd: projectRoot,
    encoding: "utf-8",
  }).trim();

  return resolve(bazelBin, "maco_gateway", "gateway_tar.tar");
}

// --- Generate .env ---

function generateEnv(): string {
  console.log("\n=== Generating production .env ===\n");

  const configPath = resolve(configDir, "config.jsonc");
  const config = parseJsonc(readFileSync(configPath, "utf-8"));

  const masterKey = fetchSecret("GATEWAY_ASCON_MASTER_KEY");
  const gatewayApiKey = fetchSecret("GATEWAY_API_KEY");

  const firebaseUrl = resolveValue(config, "gateway.firebaseUrl");
  if (!firebaseUrl) {
    console.error("Error: gateway.firebaseUrl not found in config.jsonc");
    process.exit(1);
  }

  const lines = [
    "# Generated by deploy-gateway.ts — do not edit",
    "",
    "# MaCo Gateway",
    "GATEWAY_HOST=0.0.0.0",
    "GATEWAY_PORT=5000",
    `MASTER_KEY=${masterKey}`,
    `FIREBASE_URL=${firebaseUrl}`,
    `GATEWAY_API_KEY=${gatewayApiKey}`,
    "",
  ];

  const outDir = resolve(projectRoot, "out");
  mkdirSync(outDir, { recursive: true });
  const envPath = resolve(outDir, "gateway.env");
  writeFileSync(envPath, lines.join("\n"));
  console.log(`  Written: ${envPath}`);
  return envPath;
}

// --- Deploy ---

function deploy(tarPath: string, envPath: string, host: string, remoteDir: string) {
  console.log(`\n=== Deploying to ${host}:${remoteDir} ===\n`);

  execSync(`ssh ${host} "mkdir -p ${remoteDir}"`, { stdio: "inherit" });

  // Upload and extract tarball (the tar contains a gateway/ directory)
  execSync(`scp ${tarPath} ${host}:/tmp/gateway_tar.tar`, { stdio: "inherit" });
  execSync(
    `ssh ${host} "tar xf /tmp/gateway_tar.tar -C ${remoteDir} --strip-components=1 && rm /tmp/gateway_tar.tar"`,
    { stdio: "inherit" },
  );

  // Upload .env alongside the gateway binary
  execSync(`scp ${envPath} ${host}:${remoteDir}/.env`, { stdio: "inherit" });

  console.log(`\nDeployed. Run on the Pi:`);
  console.log(`  cd ${remoteDir} && ./gateway`);
}

// --- Main ---

function main() {
  const { values } = parseArgs({
    options: {
      host: { type: "string", short: "h" },
      "remote-dir": { type: "string", default: "~/gateway" },
      "build-only": { type: "boolean", default: false },
    },
    strict: true,
  });

  if (!values["build-only"] && !values.host) {
    console.error("Usage: deploy-gateway.ts --host pi@rpi.local [--remote-dir ~/gateway]");
    console.error("       deploy-gateway.ts --build-only");
    process.exit(1);
  }

  const tarPath = buildTar();
  const envPath = generateEnv();

  if (values["build-only"]) {
    console.log(`\nBuild complete:`);
    console.log(`  Tarball: ${tarPath}`);
    console.log(`  ENV:     ${envPath}`);
  } else {
    deploy(tarPath, envPath, values.host!, values["remote-dir"]!);
  }
}

main();
