// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

/**
 * Build and deploy the MACO gateway to a Raspberry Pi.
 *
 * Architecture:
 *   The gateway runs from a Python venv on the Pi (system Python 3.11), not
 *   from a Bazel-bundled hermetic interpreter — that approach can't cross-build
 *   for aarch64 because pigweed's Bazel pip hub pulls in x86_64-only native
 *   wheels (psutil, charset_normalizer, pyyaml) we don't actually use.
 *
 *   The deploy payload contains:
 *     - maco_gateway/        gateway sources
 *     - gateway/             generated proto for the gateway service
 *     - pw_hdlc/, pw_rpc/, pw_status/, pw_protobuf_compiler/
 *                            pigweed Python sources, vendored from
 *                            third_party/pigweed (head, protobuf-6 compatible).
 *                            The PyPI `pigweed` package lags head and pins
 *                            protobuf~=5.28, which conflicts with our generated
 *                            code's runtime requirement.
 *     - requirements.txt     pip deps: httpx, ascon, python-dotenv, protobuf
 *
 * Steps:
 *   1. Build proto via Bazel (gateway service + pw_rpc/internal/packet)
 *   2. Stage payload (sources + protos + vendored pigweed + requirements.txt)
 *   3. Generate .env from config.jsonc + Google Cloud Secret Manager
 *   4. Multiplexed SCP/SSH: extract, create venv, pip install
 *
 * Usage:
 *   npx tsx scripts/deploy-gateway.ts --host maker1@maco-gateway.internal
 *   npx tsx scripts/deploy-gateway.ts --host maker1@maco-gateway.internal --remote-dir /opt/gateway
 *   npx tsx scripts/deploy-gateway.ts --build-only   # just build, no deploy
 */

import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  copyFileSync,
  readdirSync,
} from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";
import { parseArgs } from "util";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const configDir =
  process.env.OPERATIONS_CONFIG_DIR ||
  resolve(projectRoot, "..", "machine-auth-operations");

// --- Config helpers (same as generate-env.ts) ---

function parseJsonc(text: string): Record<string, unknown> {
  let result = "";
  let i = 0;
  while (i < text.length) {
    if (text[i] === '"') {
      const start = i;
      i++;
      while (i < text.length && text[i] !== '"') {
        if (text[i] === "\\") i++;
        i++;
      }
      i++;
      result += text.slice(start, i);
    } else if (text[i] === "/" && text[i + 1] === "/") {
      while (i < text.length && text[i] !== "\n") i++;
    } else if (text[i] === "/" && text[i + 1] === "*") {
      i += 2;
      while (i < text.length - 1 && !(text[i] === "*" && text[i + 1] === "/")) i++;
      i += 2;
    } else {
      result += text[i];
      i++;
    }
  }
  return JSON.parse(result);
}

function resolveValue(config: Record<string, unknown>, jsonPath: string): string {
  const parts = jsonPath.split(".");
  let current: unknown = config;
  for (const part of parts) {
    if (current == null || typeof current !== "object") return "";
    current = (current as Record<string, unknown>)[part];
  }
  if (current == null) return "";
  return String(current);
}

// --- Secret Manager ---

function fetchSecret(secretName: string): string {
  console.log(`  Fetching secret: ${secretName}`);
  try {
    return execSync(
      `gcloud secrets versions access latest --secret=${secretName}`,
      { encoding: "utf-8" },
    ).trim();
  } catch {
    console.error(`Failed to fetch secret "${secretName}". Check: gcloud config get-value project`);
    process.exit(1);
  }
}

// --- Build payload ---

// Pinned pip deps for the Pi venv. All pure-Python except `protobuf`, which
// has a manylinux aarch64 wheel on PyPI. Pigweed Python sources are vendored
// (see PIGWEED_PY_PACKAGES below), not installed from PyPI.
const REQUIREMENTS_TXT = [
  "# Generated by deploy-gateway.ts — do not edit",
  "ascon==0.0.9",
  "httpx==0.28.1",
  "protobuf>=6.33,<7",
  "python-dotenv==1.2.2",
  "",
].join("\n");

// Pigweed Python packages we vendor from third_party/pigweed/. The set is the
// transitive import closure of what maco_gateway/main.py imports. See the
// import chain reasoning in the deploy doc.
const PIGWEED_PY_PACKAGES = [
  "pw_hdlc",
  "pw_protobuf_compiler",
  "pw_rpc",
  "pw_status",
];

// (target → repo-relative destination) for protos generated by Bazel.
const PROTO_OUTPUTS: Array<{ target: string; src: string; dest: string }> = [
  {
    target: "//proto/gateway:gateway_service_py_pb2",
    src: "proto/gateway/_virtual_imports/gateway_service_proto/gateway/gateway_service_pb2.py",
    dest: "gateway/gateway_service_pb2.py",
  },
  {
    target: "@pigweed//pw_rpc:internal_packet_proto_pb2",
    src: "external/pigweed+/pw_rpc/internal/packet_pb2.py",
    dest: "pw_rpc/internal/packet_pb2.py",
  },
];

function copyDirRecursive(srcDir: string, destDir: string) {
  mkdirSync(destDir, { recursive: true });
  for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
    const srcPath = resolve(srcDir, entry.name);
    const destPath = resolve(destDir, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else if (entry.isFile()) {
      copyFileSync(srcPath, destPath);
    }
  }
}

function buildPayload(): string {
  console.log("\n=== Building gateway deploy payload ===\n");

  execSync(
    `bazelisk build ${PROTO_OUTPUTS.map((p) => p.target).join(" ")}`,
    { cwd: projectRoot, stdio: "inherit" },
  );
  const bazelBin = execSync("bazelisk info bazel-bin", {
    cwd: projectRoot,
    encoding: "utf-8",
  }).trim();

  const stage = resolve(projectRoot, "out/gateway-deploy");
  rmSync(stage, { recursive: true, force: true });
  mkdirSync(stage, { recursive: true });

  // Gateway sources.
  const sourceDir = resolve(projectRoot, "maco_gateway/maco_gateway");
  mkdirSync(resolve(stage, "maco_gateway"), { recursive: true });
  for (const file of readdirSync(sourceDir)) {
    if (file.endsWith(".py")) {
      copyFileSync(resolve(sourceDir, file), resolve(stage, "maco_gateway", file));
    }
  }

  // Vendored pigweed Python sources.
  for (const pkg of PIGWEED_PY_PACKAGES) {
    const src = resolve(projectRoot, `third_party/pigweed/${pkg}/py/${pkg}`);
    copyDirRecursive(src, resolve(stage, pkg));
  }

  // Generated proto modules.
  for (const proto of PROTO_OUTPUTS) {
    const destPath = resolve(stage, proto.dest);
    mkdirSync(dirname(destPath), { recursive: true });
    copyFileSync(resolve(bazelBin, proto.src), destPath);
  }
  // pw_rpc/internal/ needs an __init__.py to be importable as a package.
  writeFileSync(resolve(stage, "pw_rpc/internal/__init__.py"), "");

  writeFileSync(resolve(stage, "requirements.txt"), REQUIREMENTS_TXT);

  const tarPath = resolve(projectRoot, "out/gateway-deploy.tar.gz");
  execSync(`tar czf ${tarPath} -C ${stage} .`, { stdio: "inherit" });
  console.log(`  Written: ${tarPath}`);
  return tarPath;
}

// --- Generate .env ---

function generateEnv(): string {
  console.log("\n=== Generating production .env ===\n");

  const configPath = resolve(configDir, "config.jsonc");
  const config = parseJsonc(readFileSync(configPath, "utf-8"));

  const masterKey = fetchSecret("GATEWAY_ASCON_MASTER_KEY");
  const gatewayApiKey = fetchSecret("GATEWAY_API_KEY");

  const firebaseUrl = resolveValue(config, "gateway.firebaseUrl");
  if (!firebaseUrl) {
    console.error("Error: gateway.firebaseUrl not found in config.jsonc");
    process.exit(1);
  }

  const lines = [
    "# Generated by deploy-gateway.ts — do not edit",
    "",
    "# MaCo Gateway",
    "GATEWAY_HOST=0.0.0.0",
    "GATEWAY_PORT=5000",
    `MASTER_KEY=${masterKey}`,
    `FIREBASE_URL=${firebaseUrl}`,
    `GATEWAY_API_KEY=${gatewayApiKey}`,
    "",
  ];

  const outDir = resolve(projectRoot, "out");
  mkdirSync(outDir, { recursive: true });
  const envPath = resolve(outDir, "gateway.env");
  writeFileSync(envPath, lines.join("\n"));
  console.log(`  Written: ${envPath}`);
  return envPath;
}

// --- Deploy ---

function deploy(payloadPath: string, envPath: string, host: string, remoteDir: string) {
  console.log(`\n=== Deploying to ${host}:${remoteDir} ===\n`);

  // Multiplex all ssh/scp calls over a single connection so the user types
  // the password (or unlocks their key) at most once. The first command
  // opens the master; the rest reuse the control socket.
  const ctlSocket = `/tmp/ssh-deploy-gateway-${process.pid}.sock`;
  const sshOpts = `-o ControlMaster=auto -o ControlPath=${ctlSocket} -o ControlPersist=60s`;

  // Single remote script: extract payload, ensure venv, sync deps.
  // `pip install -r` is idempotent and fast when nothing changed.
  const remoteScript = [
    `set -e`,
    `mkdir -p ${remoteDir}`,
    `cd ${remoteDir}`,
    `tar xzf /tmp/gateway-deploy.tar.gz`,
    `rm /tmp/gateway-deploy.tar.gz`,
    `[ -d venv ] || python3 -m venv venv`,
    `venv/bin/pip install --quiet --upgrade pip`,
    `venv/bin/pip install --quiet -r requirements.txt`,
  ].join(" && ");

  try {
    execSync(`scp ${sshOpts} ${payloadPath} ${host}:/tmp/gateway-deploy.tar.gz`, {
      stdio: "inherit",
    });
    execSync(`ssh ${sshOpts} ${host} '${remoteScript}'`, { stdio: "inherit" });
    execSync(`scp ${sshOpts} ${envPath} ${host}:${remoteDir}/.env`, { stdio: "inherit" });
  } finally {
    try {
      execSync(`ssh ${sshOpts} -O exit ${host}`, { stdio: "ignore" });
    } catch {
      // Master already torn down (e.g. earlier command failed before opening it).
    }
  }

  console.log(`\nDeployed. Run on the Pi:`);
  console.log(`  cd ${remoteDir} && venv/bin/python -m maco_gateway.main`);
}

// --- Main ---

function main() {
  const { values } = parseArgs({
    options: {
      host: { type: "string", short: "h" },
      "remote-dir": { type: "string", default: "~/gateway" },
      "build-only": { type: "boolean", default: false },
    },
    strict: true,
  });

  if (!values["build-only"] && !values.host) {
    console.error("Usage: deploy-gateway.ts --host maker1@maco-gateway.internal [--remote-dir ~/gateway]");
    console.error("       deploy-gateway.ts --build-only");
    process.exit(1);
  }

  const payloadPath = buildPayload();
  const envPath = generateEnv();

  if (values["build-only"]) {
    console.log(`\nBuild complete:`);
    console.log(`  Payload: ${payloadPath}`);
    console.log(`  ENV:     ${envPath}`);
  } else {
    deploy(payloadPath, envPath, values.host!, values["remote-dir"]!);
  }
}

main();
