// Copyright Offene Werkstatt Wädenswil
// SPDX-License-Identifier: MIT

// Test-run secret pinning for the port-block broker (see port-block.ts).
// Separate module so the pure content builder is importable from tests
// without executing the broker's top-level main().

/**
 * Every `defineSecret(...)` name in functions/src. Keep in sync with
 * `grep -rn 'defineSecret(' functions/src/`. The port-block broker pins
 * all of them in `.secret.local` during test runs — any secret missing
 * from that file makes the functions emulator fall back to Cloud Secret
 * Manager, which silently pulls *production* values on an authenticated
 * developer machine (CI is unauthenticated and falls back to .env.test,
 * so the same suite is green in CI and red locally).
 */
export const FUNCTION_SECRET_NAMES = [
  "DIVERSIFICATION_MASTER_KEY",
  "GATEWAY_API_KEY",
  "KIOSK_BEARER_KEY",
  "PARTICLE_TOKEN",
  "RESEND_API_KEY",
  "TERMINAL_KEY",
];

/**
 * Build the `.secret.local` content for a test run: one line per known
 * secret, sourced from the committed `.env.test` fixture where a value
 * exists, otherwise a deterministic dummy — the point is that no secret
 * resolution ever escapes to Cloud Secret Manager.
 */
export function buildTestSecretFileContent(envTestContent: string): string {
  const values = new Map<string, string>();
  for (const line of envTestContent.split("\n")) {
    const match = /^([A-Z0-9_]+)=(.*)$/.exec(line);
    if (match) values.set(match[1], match[2]);
  }
  const lines = FUNCTION_SECRET_NAMES.map(
    (name) =>
      `${name}=${values.get(name) ?? `ci-test-dummy-${name.toLowerCase()}`}`
  );
  return (
    "# Generated by scripts/port-block.ts for this test run — do not edit.\n" +
    "# Pins every functions defineSecret to test values so the emulator\n" +
    "# never reads production secrets from Cloud Secret Manager.\n" +
    lines.join("\n") +
    "\n"
  );
}
