// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { FirstAuthentication, FirstAuthenticationT } from '../../oww/session/first-authentication.js';
import { RecentAuthentication, RecentAuthenticationT } from '../../oww/session/recent-authentication.js';


export enum Authentication {
  NONE = 0,
  FirstAuthentication = 1,
  RecentAuthentication = 2
}

export function unionToAuthentication(
  type: Authentication,
  accessor: (obj:FirstAuthentication|RecentAuthentication) => FirstAuthentication|RecentAuthentication|null
): FirstAuthentication|RecentAuthentication|null {
  switch(Authentication[type]) {
    case 'NONE': return null; 
    case 'FirstAuthentication': return accessor(new FirstAuthentication())! as FirstAuthentication;
    case 'RecentAuthentication': return accessor(new RecentAuthentication())! as RecentAuthentication;
    default: return null;
  }
}

export function unionListToAuthentication(
  type: Authentication, 
  accessor: (index: number, obj:FirstAuthentication|RecentAuthentication) => FirstAuthentication|RecentAuthentication|null, 
  index: number
): FirstAuthentication|RecentAuthentication|null {
  switch(Authentication[type]) {
    case 'NONE': return null; 
    case 'FirstAuthentication': return accessor(index, new FirstAuthentication())! as FirstAuthentication;
    case 'RecentAuthentication': return accessor(index, new RecentAuthentication())! as RecentAuthentication;
    default: return null;
  }
}
