// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class StateRejected implements flatbuffers.IUnpackableObject<StateRejectedT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StateRejected {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStateRejected(bb:flatbuffers.ByteBuffer, obj?:StateRejected):StateRejected {
  return (obj || new StateRejected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStateRejected(bb:flatbuffers.ByteBuffer, obj?:StateRejected):StateRejected {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateRejected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startStateRejected(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static endStateRejected(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStateRejected(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  StateRejected.startStateRejected(builder);
  StateRejected.addMessage(builder, messageOffset);
  return StateRejected.endStateRejected(builder);
}

serialize():Uint8Array {
  return this.bb!.bytes();
}

static deserialize(buffer: Uint8Array):StateRejected {
  return StateRejected.getRootAsStateRejected(new flatbuffers.ByteBuffer(buffer))
}

unpack(): StateRejectedT {
  return new StateRejectedT(
    this.message()
  );
}


unpackTo(_o: StateRejectedT): void {
  _o.message = this.message();
}
}

export class StateRejectedT implements flatbuffers.IGeneratedObject {
constructor(
  public message: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const message = (this.message !== null ? builder.createString(this.message!) : 0);

  return StateRejected.createStateRejected(builder,
    message
  );
}
}
