/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ReportRouteImport } from "./routes/_report"
import { Route as MaterialRouteImport } from "./routes/_material"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ReportReportRouteImport } from "./routes/_report/report"
import { Route as AuthenticatedVisitRouteImport } from "./routes/_authenticated/visit"
import { Route as AuthenticatedUsageRouteImport } from "./routes/_authenticated/usage"
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile"
import { Route as AuthenticatedCompleteProfileRouteImport } from "./routes/_authenticated/complete-profile"
import { Route as AuthenticatedAdminRouteImport } from "./routes/_authenticated/admin"
import { Route as MaterialMaterialAddRouteImport } from "./routes/_material/material.add"
import { Route as AuthenticatedAdminUsersRouteImport } from "./routes/_authenticated/admin/users"
import { Route as AuthenticatedAdminTerminalsRouteImport } from "./routes/_authenticated/admin/terminals"
import { Route as AuthenticatedAdminSessionsRouteImport } from "./routes/_authenticated/admin/sessions"
import { Route as AuthenticatedAdminPriceListsRouteImport } from "./routes/_authenticated/admin/price-lists"
import { Route as AuthenticatedAdminPermissionsRouteImport } from "./routes/_authenticated/admin/permissions"
import { Route as AuthenticatedAdminMaterialsRouteImport } from "./routes/_authenticated/admin/materials"
import { Route as AuthenticatedAdminMachinesRouteImport } from "./routes/_authenticated/admin/machines"
import { Route as AuthenticatedAdminCheckoutsRouteImport } from "./routes/_authenticated/admin/checkouts"
import { Route as AuthenticatedAdminAuditRouteImport } from "./routes/_authenticated/admin/audit"
import { Route as AuthenticatedAdminUsersIndexRouteImport } from "./routes/_authenticated/admin/users/index"
import { Route as AuthenticatedAdminPriceListsIndexRouteImport } from "./routes/_authenticated/admin/price-lists/index"
import { Route as AuthenticatedAdminPermissionsIndexRouteImport } from "./routes/_authenticated/admin/permissions/index"
import { Route as AuthenticatedAdminMaterialsIndexRouteImport } from "./routes/_authenticated/admin/materials/index"
import { Route as AuthenticatedAdminMachinesIndexRouteImport } from "./routes/_authenticated/admin/machines/index"
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from "./routes/_authenticated/admin/users/$userId"
import { Route as AuthenticatedAdminPriceListsPriceListIdRouteImport } from "./routes/_authenticated/admin/price-lists/$priceListId"
import { Route as AuthenticatedAdminPermissionsPermissionIdRouteImport } from "./routes/_authenticated/admin/permissions/$permissionId"
import { Route as AuthenticatedAdminMaterialsMaterialIdRouteImport } from "./routes/_authenticated/admin/materials/$materialId"
import { Route as AuthenticatedAdminMachinesMachineIdRouteImport } from "./routes/_authenticated/admin/machines/$machineId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: "/_report",
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRoute = MaterialRouteImport.update({
  id: "/_material",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportRoute = ReportReportRouteImport.update({
  id: "/report",
  path: "/report",
  getParentRoute: () => ReportRoute,
} as any)
const AuthenticatedVisitRoute = AuthenticatedVisitRouteImport.update({
  id: "/visit",
  path: "/visit",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: "/complete-profile",
    path: "/complete-profile",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MaterialMaterialAddRoute = MaterialMaterialAddRouteImport.update({
  id: "/material/add",
  path: "/material/add",
  getParentRoute: () => MaterialRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTerminalsRoute =
  AuthenticatedAdminTerminalsRouteImport.update({
    id: "/terminals",
    path: "/terminals",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: "/sessions",
    path: "/sessions",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPriceListsRoute =
  AuthenticatedAdminPriceListsRouteImport.update({
    id: "/price-lists",
    path: "/price-lists",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: "/permissions",
    path: "/permissions",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaterialsRoute =
  AuthenticatedAdminMaterialsRouteImport.update({
    id: "/materials",
    path: "/materials",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMachinesRoute =
  AuthenticatedAdminMachinesRouteImport.update({
    id: "/machines",
    path: "/machines",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCheckoutsRoute =
  AuthenticatedAdminCheckoutsRouteImport.update({
    id: "/checkouts",
    path: "/checkouts",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminPriceListsIndexRoute =
  AuthenticatedAdminPriceListsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedAdminPriceListsRoute,
  } as any)
const AuthenticatedAdminPermissionsIndexRoute =
  AuthenticatedAdminPermissionsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedAdminPermissionsRoute,
  } as any)
const AuthenticatedAdminMaterialsIndexRoute =
  AuthenticatedAdminMaterialsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedAdminMaterialsRoute,
  } as any)
const AuthenticatedAdminMachinesIndexRoute =
  AuthenticatedAdminMachinesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedAdminMachinesRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: "/$userId",
    path: "/$userId",
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminPriceListsPriceListIdRoute =
  AuthenticatedAdminPriceListsPriceListIdRouteImport.update({
    id: "/$priceListId",
    path: "/$priceListId",
    getParentRoute: () => AuthenticatedAdminPriceListsRoute,
  } as any)
const AuthenticatedAdminPermissionsPermissionIdRoute =
  AuthenticatedAdminPermissionsPermissionIdRouteImport.update({
    id: "/$permissionId",
    path: "/$permissionId",
    getParentRoute: () => AuthenticatedAdminPermissionsRoute,
  } as any)
const AuthenticatedAdminMaterialsMaterialIdRoute =
  AuthenticatedAdminMaterialsMaterialIdRouteImport.update({
    id: "/$materialId",
    path: "/$materialId",
    getParentRoute: () => AuthenticatedAdminMaterialsRoute,
  } as any)
const AuthenticatedAdminMachinesMachineIdRoute =
  AuthenticatedAdminMachinesMachineIdRouteImport.update({
    id: "/$machineId",
    path: "/$machineId",
    getParentRoute: () => AuthenticatedAdminMachinesRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/admin": typeof AuthenticatedAdminRouteWithChildren
  "/complete-profile": typeof AuthenticatedCompleteProfileRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/usage": typeof AuthenticatedUsageRoute
  "/visit": typeof AuthenticatedVisitRoute
  "/report": typeof ReportReportRoute
  "/admin/audit": typeof AuthenticatedAdminAuditRoute
  "/admin/checkouts": typeof AuthenticatedAdminCheckoutsRoute
  "/admin/machines": typeof AuthenticatedAdminMachinesRouteWithChildren
  "/admin/materials": typeof AuthenticatedAdminMaterialsRouteWithChildren
  "/admin/permissions": typeof AuthenticatedAdminPermissionsRouteWithChildren
  "/admin/price-lists": typeof AuthenticatedAdminPriceListsRouteWithChildren
  "/admin/sessions": typeof AuthenticatedAdminSessionsRoute
  "/admin/terminals": typeof AuthenticatedAdminTerminalsRoute
  "/admin/users": typeof AuthenticatedAdminUsersRouteWithChildren
  "/material/add": typeof MaterialMaterialAddRoute
  "/admin/machines/$machineId": typeof AuthenticatedAdminMachinesMachineIdRoute
  "/admin/materials/$materialId": typeof AuthenticatedAdminMaterialsMaterialIdRoute
  "/admin/permissions/$permissionId": typeof AuthenticatedAdminPermissionsPermissionIdRoute
  "/admin/price-lists/$priceListId": typeof AuthenticatedAdminPriceListsPriceListIdRoute
  "/admin/users/$userId": typeof AuthenticatedAdminUsersUserIdRoute
  "/admin/machines/": typeof AuthenticatedAdminMachinesIndexRoute
  "/admin/materials/": typeof AuthenticatedAdminMaterialsIndexRoute
  "/admin/permissions/": typeof AuthenticatedAdminPermissionsIndexRoute
  "/admin/price-lists/": typeof AuthenticatedAdminPriceListsIndexRoute
  "/admin/users/": typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/admin": typeof AuthenticatedAdminRouteWithChildren
  "/complete-profile": typeof AuthenticatedCompleteProfileRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/usage": typeof AuthenticatedUsageRoute
  "/visit": typeof AuthenticatedVisitRoute
  "/report": typeof ReportReportRoute
  "/admin/audit": typeof AuthenticatedAdminAuditRoute
  "/admin/checkouts": typeof AuthenticatedAdminCheckoutsRoute
  "/admin/sessions": typeof AuthenticatedAdminSessionsRoute
  "/admin/terminals": typeof AuthenticatedAdminTerminalsRoute
  "/material/add": typeof MaterialMaterialAddRoute
  "/admin/machines/$machineId": typeof AuthenticatedAdminMachinesMachineIdRoute
  "/admin/materials/$materialId": typeof AuthenticatedAdminMaterialsMaterialIdRoute
  "/admin/permissions/$permissionId": typeof AuthenticatedAdminPermissionsPermissionIdRoute
  "/admin/price-lists/$priceListId": typeof AuthenticatedAdminPriceListsPriceListIdRoute
  "/admin/users/$userId": typeof AuthenticatedAdminUsersUserIdRoute
  "/admin/machines": typeof AuthenticatedAdminMachinesIndexRoute
  "/admin/materials": typeof AuthenticatedAdminMaterialsIndexRoute
  "/admin/permissions": typeof AuthenticatedAdminPermissionsIndexRoute
  "/admin/price-lists": typeof AuthenticatedAdminPriceListsIndexRoute
  "/admin/users": typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/_material": typeof MaterialRouteWithChildren
  "/_report": typeof ReportRouteWithChildren
  "/login": typeof LoginRoute
  "/_authenticated/admin": typeof AuthenticatedAdminRouteWithChildren
  "/_authenticated/complete-profile": typeof AuthenticatedCompleteProfileRoute
  "/_authenticated/profile": typeof AuthenticatedProfileRoute
  "/_authenticated/usage": typeof AuthenticatedUsageRoute
  "/_authenticated/visit": typeof AuthenticatedVisitRoute
  "/_report/report": typeof ReportReportRoute
  "/_authenticated/admin/audit": typeof AuthenticatedAdminAuditRoute
  "/_authenticated/admin/checkouts": typeof AuthenticatedAdminCheckoutsRoute
  "/_authenticated/admin/machines": typeof AuthenticatedAdminMachinesRouteWithChildren
  "/_authenticated/admin/materials": typeof AuthenticatedAdminMaterialsRouteWithChildren
  "/_authenticated/admin/permissions": typeof AuthenticatedAdminPermissionsRouteWithChildren
  "/_authenticated/admin/price-lists": typeof AuthenticatedAdminPriceListsRouteWithChildren
  "/_authenticated/admin/sessions": typeof AuthenticatedAdminSessionsRoute
  "/_authenticated/admin/terminals": typeof AuthenticatedAdminTerminalsRoute
  "/_authenticated/admin/users": typeof AuthenticatedAdminUsersRouteWithChildren
  "/_material/material/add": typeof MaterialMaterialAddRoute
  "/_authenticated/admin/machines/$machineId": typeof AuthenticatedAdminMachinesMachineIdRoute
  "/_authenticated/admin/materials/$materialId": typeof AuthenticatedAdminMaterialsMaterialIdRoute
  "/_authenticated/admin/permissions/$permissionId": typeof AuthenticatedAdminPermissionsPermissionIdRoute
  "/_authenticated/admin/price-lists/$priceListId": typeof AuthenticatedAdminPriceListsPriceListIdRoute
  "/_authenticated/admin/users/$userId": typeof AuthenticatedAdminUsersUserIdRoute
  "/_authenticated/admin/machines/": typeof AuthenticatedAdminMachinesIndexRoute
  "/_authenticated/admin/materials/": typeof AuthenticatedAdminMaterialsIndexRoute
  "/_authenticated/admin/permissions/": typeof AuthenticatedAdminPermissionsIndexRoute
  "/_authenticated/admin/price-lists/": typeof AuthenticatedAdminPriceListsIndexRoute
  "/_authenticated/admin/users/": typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/admin"
    | "/complete-profile"
    | "/profile"
    | "/usage"
    | "/visit"
    | "/report"
    | "/admin/audit"
    | "/admin/checkouts"
    | "/admin/machines"
    | "/admin/materials"
    | "/admin/permissions"
    | "/admin/price-lists"
    | "/admin/sessions"
    | "/admin/terminals"
    | "/admin/users"
    | "/material/add"
    | "/admin/machines/$machineId"
    | "/admin/materials/$materialId"
    | "/admin/permissions/$permissionId"
    | "/admin/price-lists/$priceListId"
    | "/admin/users/$userId"
    | "/admin/machines/"
    | "/admin/materials/"
    | "/admin/permissions/"
    | "/admin/price-lists/"
    | "/admin/users/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/admin"
    | "/complete-profile"
    | "/profile"
    | "/usage"
    | "/visit"
    | "/report"
    | "/admin/audit"
    | "/admin/checkouts"
    | "/admin/sessions"
    | "/admin/terminals"
    | "/material/add"
    | "/admin/machines/$machineId"
    | "/admin/materials/$materialId"
    | "/admin/permissions/$permissionId"
    | "/admin/price-lists/$priceListId"
    | "/admin/users/$userId"
    | "/admin/machines"
    | "/admin/materials"
    | "/admin/permissions"
    | "/admin/price-lists"
    | "/admin/users"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_material"
    | "/_report"
    | "/login"
    | "/_authenticated/admin"
    | "/_authenticated/complete-profile"
    | "/_authenticated/profile"
    | "/_authenticated/usage"
    | "/_authenticated/visit"
    | "/_report/report"
    | "/_authenticated/admin/audit"
    | "/_authenticated/admin/checkouts"
    | "/_authenticated/admin/machines"
    | "/_authenticated/admin/materials"
    | "/_authenticated/admin/permissions"
    | "/_authenticated/admin/price-lists"
    | "/_authenticated/admin/sessions"
    | "/_authenticated/admin/terminals"
    | "/_authenticated/admin/users"
    | "/_material/material/add"
    | "/_authenticated/admin/machines/$machineId"
    | "/_authenticated/admin/materials/$materialId"
    | "/_authenticated/admin/permissions/$permissionId"
    | "/_authenticated/admin/price-lists/$priceListId"
    | "/_authenticated/admin/users/$userId"
    | "/_authenticated/admin/machines/"
    | "/_authenticated/admin/materials/"
    | "/_authenticated/admin/permissions/"
    | "/_authenticated/admin/price-lists/"
    | "/_authenticated/admin/users/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  MaterialRoute: typeof MaterialRouteWithChildren
  ReportRoute: typeof ReportRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_report": {
      id: "/_report"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_material": {
      id: "/_material"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_report/report": {
      id: "/_report/report"
      path: "/report"
      fullPath: "/report"
      preLoaderRoute: typeof ReportReportRouteImport
      parentRoute: typeof ReportRoute
    }
    "/_authenticated/visit": {
      id: "/_authenticated/visit"
      path: "/visit"
      fullPath: "/visit"
      preLoaderRoute: typeof AuthenticatedVisitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/usage": {
      id: "/_authenticated/usage"
      path: "/usage"
      fullPath: "/usage"
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/complete-profile": {
      id: "/_authenticated/complete-profile"
      path: "/complete-profile"
      fullPath: "/complete-profile"
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/admin": {
      id: "/_authenticated/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_material/material/add": {
      id: "/_material/material/add"
      path: "/material/add"
      fullPath: "/material/add"
      preLoaderRoute: typeof MaterialMaterialAddRouteImport
      parentRoute: typeof MaterialRoute
    }
    "/_authenticated/admin/users": {
      id: "/_authenticated/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/terminals": {
      id: "/_authenticated/admin/terminals"
      path: "/terminals"
      fullPath: "/admin/terminals"
      preLoaderRoute: typeof AuthenticatedAdminTerminalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/sessions": {
      id: "/_authenticated/admin/sessions"
      path: "/sessions"
      fullPath: "/admin/sessions"
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/price-lists": {
      id: "/_authenticated/admin/price-lists"
      path: "/price-lists"
      fullPath: "/admin/price-lists"
      preLoaderRoute: typeof AuthenticatedAdminPriceListsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/permissions": {
      id: "/_authenticated/admin/permissions"
      path: "/permissions"
      fullPath: "/admin/permissions"
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/materials": {
      id: "/_authenticated/admin/materials"
      path: "/materials"
      fullPath: "/admin/materials"
      preLoaderRoute: typeof AuthenticatedAdminMaterialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/machines": {
      id: "/_authenticated/admin/machines"
      path: "/machines"
      fullPath: "/admin/machines"
      preLoaderRoute: typeof AuthenticatedAdminMachinesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/checkouts": {
      id: "/_authenticated/admin/checkouts"
      path: "/checkouts"
      fullPath: "/admin/checkouts"
      preLoaderRoute: typeof AuthenticatedAdminCheckoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/audit": {
      id: "/_authenticated/admin/audit"
      path: "/audit"
      fullPath: "/admin/audit"
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    "/_authenticated/admin/users/": {
      id: "/_authenticated/admin/users/"
      path: "/"
      fullPath: "/admin/users/"
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    "/_authenticated/admin/price-lists/": {
      id: "/_authenticated/admin/price-lists/"
      path: "/"
      fullPath: "/admin/price-lists/"
      preLoaderRoute: typeof AuthenticatedAdminPriceListsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPriceListsRoute
    }
    "/_authenticated/admin/permissions/": {
      id: "/_authenticated/admin/permissions/"
      path: "/"
      fullPath: "/admin/permissions/"
      preLoaderRoute: typeof AuthenticatedAdminPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPermissionsRoute
    }
    "/_authenticated/admin/materials/": {
      id: "/_authenticated/admin/materials/"
      path: "/"
      fullPath: "/admin/materials/"
      preLoaderRoute: typeof AuthenticatedAdminMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminMaterialsRoute
    }
    "/_authenticated/admin/machines/": {
      id: "/_authenticated/admin/machines/"
      path: "/"
      fullPath: "/admin/machines/"
      preLoaderRoute: typeof AuthenticatedAdminMachinesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminMachinesRoute
    }
    "/_authenticated/admin/users/$userId": {
      id: "/_authenticated/admin/users/$userId"
      path: "/$userId"
      fullPath: "/admin/users/$userId"
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    "/_authenticated/admin/price-lists/$priceListId": {
      id: "/_authenticated/admin/price-lists/$priceListId"
      path: "/$priceListId"
      fullPath: "/admin/price-lists/$priceListId"
      preLoaderRoute: typeof AuthenticatedAdminPriceListsPriceListIdRouteImport
      parentRoute: typeof AuthenticatedAdminPriceListsRoute
    }
    "/_authenticated/admin/permissions/$permissionId": {
      id: "/_authenticated/admin/permissions/$permissionId"
      path: "/$permissionId"
      fullPath: "/admin/permissions/$permissionId"
      preLoaderRoute: typeof AuthenticatedAdminPermissionsPermissionIdRouteImport
      parentRoute: typeof AuthenticatedAdminPermissionsRoute
    }
    "/_authenticated/admin/materials/$materialId": {
      id: "/_authenticated/admin/materials/$materialId"
      path: "/$materialId"
      fullPath: "/admin/materials/$materialId"
      preLoaderRoute: typeof AuthenticatedAdminMaterialsMaterialIdRouteImport
      parentRoute: typeof AuthenticatedAdminMaterialsRoute
    }
    "/_authenticated/admin/machines/$machineId": {
      id: "/_authenticated/admin/machines/$machineId"
      path: "/$machineId"
      fullPath: "/admin/machines/$machineId"
      preLoaderRoute: typeof AuthenticatedAdminMachinesMachineIdRouteImport
      parentRoute: typeof AuthenticatedAdminMachinesRoute
    }
  }
}

interface AuthenticatedAdminMachinesRouteChildren {
  AuthenticatedAdminMachinesMachineIdRoute: typeof AuthenticatedAdminMachinesMachineIdRoute
  AuthenticatedAdminMachinesIndexRoute: typeof AuthenticatedAdminMachinesIndexRoute
}

const AuthenticatedAdminMachinesRouteChildren: AuthenticatedAdminMachinesRouteChildren =
  {
    AuthenticatedAdminMachinesMachineIdRoute:
      AuthenticatedAdminMachinesMachineIdRoute,
    AuthenticatedAdminMachinesIndexRoute: AuthenticatedAdminMachinesIndexRoute,
  }

const AuthenticatedAdminMachinesRouteWithChildren =
  AuthenticatedAdminMachinesRoute._addFileChildren(
    AuthenticatedAdminMachinesRouteChildren,
  )

interface AuthenticatedAdminMaterialsRouteChildren {
  AuthenticatedAdminMaterialsMaterialIdRoute: typeof AuthenticatedAdminMaterialsMaterialIdRoute
  AuthenticatedAdminMaterialsIndexRoute: typeof AuthenticatedAdminMaterialsIndexRoute
}

const AuthenticatedAdminMaterialsRouteChildren: AuthenticatedAdminMaterialsRouteChildren =
  {
    AuthenticatedAdminMaterialsMaterialIdRoute:
      AuthenticatedAdminMaterialsMaterialIdRoute,
    AuthenticatedAdminMaterialsIndexRoute:
      AuthenticatedAdminMaterialsIndexRoute,
  }

const AuthenticatedAdminMaterialsRouteWithChildren =
  AuthenticatedAdminMaterialsRoute._addFileChildren(
    AuthenticatedAdminMaterialsRouteChildren,
  )

interface AuthenticatedAdminPermissionsRouteChildren {
  AuthenticatedAdminPermissionsPermissionIdRoute: typeof AuthenticatedAdminPermissionsPermissionIdRoute
  AuthenticatedAdminPermissionsIndexRoute: typeof AuthenticatedAdminPermissionsIndexRoute
}

const AuthenticatedAdminPermissionsRouteChildren: AuthenticatedAdminPermissionsRouteChildren =
  {
    AuthenticatedAdminPermissionsPermissionIdRoute:
      AuthenticatedAdminPermissionsPermissionIdRoute,
    AuthenticatedAdminPermissionsIndexRoute:
      AuthenticatedAdminPermissionsIndexRoute,
  }

const AuthenticatedAdminPermissionsRouteWithChildren =
  AuthenticatedAdminPermissionsRoute._addFileChildren(
    AuthenticatedAdminPermissionsRouteChildren,
  )

interface AuthenticatedAdminPriceListsRouteChildren {
  AuthenticatedAdminPriceListsPriceListIdRoute: typeof AuthenticatedAdminPriceListsPriceListIdRoute
  AuthenticatedAdminPriceListsIndexRoute: typeof AuthenticatedAdminPriceListsIndexRoute
}

const AuthenticatedAdminPriceListsRouteChildren: AuthenticatedAdminPriceListsRouteChildren =
  {
    AuthenticatedAdminPriceListsPriceListIdRoute:
      AuthenticatedAdminPriceListsPriceListIdRoute,
    AuthenticatedAdminPriceListsIndexRoute:
      AuthenticatedAdminPriceListsIndexRoute,
  }

const AuthenticatedAdminPriceListsRouteWithChildren =
  AuthenticatedAdminPriceListsRoute._addFileChildren(
    AuthenticatedAdminPriceListsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCheckoutsRoute: typeof AuthenticatedAdminCheckoutsRoute
  AuthenticatedAdminMachinesRoute: typeof AuthenticatedAdminMachinesRouteWithChildren
  AuthenticatedAdminMaterialsRoute: typeof AuthenticatedAdminMaterialsRouteWithChildren
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRouteWithChildren
  AuthenticatedAdminPriceListsRoute: typeof AuthenticatedAdminPriceListsRouteWithChildren
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminTerminalsRoute: typeof AuthenticatedAdminTerminalsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCheckoutsRoute: AuthenticatedAdminCheckoutsRoute,
  AuthenticatedAdminMachinesRoute: AuthenticatedAdminMachinesRouteWithChildren,
  AuthenticatedAdminMaterialsRoute:
    AuthenticatedAdminMaterialsRouteWithChildren,
  AuthenticatedAdminPermissionsRoute:
    AuthenticatedAdminPermissionsRouteWithChildren,
  AuthenticatedAdminPriceListsRoute:
    AuthenticatedAdminPriceListsRouteWithChildren,
  AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
  AuthenticatedAdminTerminalsRoute: AuthenticatedAdminTerminalsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedVisitRoute: typeof AuthenticatedVisitRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedVisitRoute: AuthenticatedVisitRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MaterialRouteChildren {
  MaterialMaterialAddRoute: typeof MaterialMaterialAddRoute
}

const MaterialRouteChildren: MaterialRouteChildren = {
  MaterialMaterialAddRoute: MaterialMaterialAddRoute,
}

const MaterialRouteWithChildren = MaterialRoute._addFileChildren(
  MaterialRouteChildren,
)

interface ReportRouteChildren {
  ReportReportRoute: typeof ReportReportRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportReportRoute: ReportReportRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  MaterialRoute: MaterialRouteWithChildren,
  ReportRoute: ReportRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
