// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: firebase_rpc/usage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TagUid } from "../common";

export const protobufPackage = "maco.proto.firebase_rpc";

/** Reason for session checkout */
export interface CheckOutReason {
  reason?:
    | //
    /** Checked out via UI */
    { $case: "ui"; ui: ReasonUi }
    | //
    /** Another tag/user checked in on the same terminal */
    { $case: "otherTag"; otherTag: ReasonCheckInOtherTag }
    | //
    /** User checked in on another machine */
    { $case: "otherMachine"; otherMachine: ReasonCheckInOtherMachine }
    | //
    /** Session timed out */
    { $case: "timeout"; timeout: ReasonTimeout }
    | //
    /** User used self-checkout */
    { $case: "selfCheckout"; selfCheckout: ReasonSelfCheckout }
    | undefined;
}

export interface ReasonUi {
}

export interface ReasonCheckInOtherTag {
  tokenId: TagUid | undefined;
  userId: string;
}

export interface ReasonCheckInOtherMachine {
  machineId: string;
}

export interface ReasonTimeout {
}

export interface ReasonSelfCheckout {
}

/** Single machine usage record */
export interface MachineUsage {
  /** Firebase session ID */
  sessionId: string;
  /** Check-in timestamp (unix timestamp) */
  checkIn: bigint;
  /** Check-out timestamp (unix timestamp), 0 if still active */
  checkOut: bigint;
  /** Reason for checkout */
  reason: CheckOutReason | undefined;
}

/** Collection of usage records for a machine */
export interface MachineUsageHistory {
  /** Firebase machine ID */
  machineId: string;
  /** Usage records to upload */
  records: MachineUsage[];
}

/** UploadUsage RPC - uploads machine usage history to Firebase */
export interface UploadUsageRequest {
  history: MachineUsageHistory | undefined;
}

export interface UploadUsageResponse {
  success: boolean;
}

function createBaseCheckOutReason(): CheckOutReason {
  return { reason: undefined };
}

export const CheckOutReason: MessageFns<CheckOutReason> = {
  encode(message: CheckOutReason, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.reason?.$case) {
      case "ui":
        ReasonUi.encode(message.reason.ui, writer.uint32(10).fork()).join();
        break;
      case "otherTag":
        ReasonCheckInOtherTag.encode(message.reason.otherTag, writer.uint32(18).fork()).join();
        break;
      case "otherMachine":
        ReasonCheckInOtherMachine.encode(message.reason.otherMachine, writer.uint32(26).fork()).join();
        break;
      case "timeout":
        ReasonTimeout.encode(message.reason.timeout, writer.uint32(34).fork()).join();
        break;
      case "selfCheckout":
        ReasonSelfCheckout.encode(message.reason.selfCheckout, writer.uint32(42).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckOutReason {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckOutReason();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reason = { $case: "ui", ui: ReasonUi.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = { $case: "otherTag", otherTag: ReasonCheckInOtherTag.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reason = {
            $case: "otherMachine",
            otherMachine: ReasonCheckInOtherMachine.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = { $case: "timeout", timeout: ReasonTimeout.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.reason = { $case: "selfCheckout", selfCheckout: ReasonSelfCheckout.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CheckOutReason>): CheckOutReason {
    return CheckOutReason.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CheckOutReason>): CheckOutReason {
    const message = createBaseCheckOutReason();
    switch (object.reason?.$case) {
      case "ui": {
        if (object.reason?.ui !== undefined && object.reason?.ui !== null) {
          message.reason = { $case: "ui", ui: ReasonUi.fromPartial(object.reason.ui) };
        }
        break;
      }
      case "otherTag": {
        if (object.reason?.otherTag !== undefined && object.reason?.otherTag !== null) {
          message.reason = { $case: "otherTag", otherTag: ReasonCheckInOtherTag.fromPartial(object.reason.otherTag) };
        }
        break;
      }
      case "otherMachine": {
        if (object.reason?.otherMachine !== undefined && object.reason?.otherMachine !== null) {
          message.reason = {
            $case: "otherMachine",
            otherMachine: ReasonCheckInOtherMachine.fromPartial(object.reason.otherMachine),
          };
        }
        break;
      }
      case "timeout": {
        if (object.reason?.timeout !== undefined && object.reason?.timeout !== null) {
          message.reason = { $case: "timeout", timeout: ReasonTimeout.fromPartial(object.reason.timeout) };
        }
        break;
      }
      case "selfCheckout": {
        if (object.reason?.selfCheckout !== undefined && object.reason?.selfCheckout !== null) {
          message.reason = {
            $case: "selfCheckout",
            selfCheckout: ReasonSelfCheckout.fromPartial(object.reason.selfCheckout),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseReasonUi(): ReasonUi {
  return {};
}

export const ReasonUi: MessageFns<ReasonUi> = {
  encode(_: ReasonUi, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReasonUi {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReasonUi();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReasonUi>): ReasonUi {
    return ReasonUi.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ReasonUi>): ReasonUi {
    const message = createBaseReasonUi();
    return message;
  },
};

function createBaseReasonCheckInOtherTag(): ReasonCheckInOtherTag {
  return { tokenId: undefined, userId: "" };
}

export const ReasonCheckInOtherTag: MessageFns<ReasonCheckInOtherTag> = {
  encode(message: ReasonCheckInOtherTag, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenId !== undefined) {
      TagUid.encode(message.tokenId, writer.uint32(10).fork()).join();
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReasonCheckInOtherTag {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReasonCheckInOtherTag();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokenId = TagUid.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReasonCheckInOtherTag>): ReasonCheckInOtherTag {
    return ReasonCheckInOtherTag.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReasonCheckInOtherTag>): ReasonCheckInOtherTag {
    const message = createBaseReasonCheckInOtherTag();
    message.tokenId = (object.tokenId !== undefined && object.tokenId !== null)
      ? TagUid.fromPartial(object.tokenId)
      : undefined;
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseReasonCheckInOtherMachine(): ReasonCheckInOtherMachine {
  return { machineId: "" };
}

export const ReasonCheckInOtherMachine: MessageFns<ReasonCheckInOtherMachine> = {
  encode(message: ReasonCheckInOtherMachine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.machineId !== "") {
      writer.uint32(10).string(message.machineId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReasonCheckInOtherMachine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReasonCheckInOtherMachine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.machineId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReasonCheckInOtherMachine>): ReasonCheckInOtherMachine {
    return ReasonCheckInOtherMachine.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReasonCheckInOtherMachine>): ReasonCheckInOtherMachine {
    const message = createBaseReasonCheckInOtherMachine();
    message.machineId = object.machineId ?? "";
    return message;
  },
};

function createBaseReasonTimeout(): ReasonTimeout {
  return {};
}

export const ReasonTimeout: MessageFns<ReasonTimeout> = {
  encode(_: ReasonTimeout, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReasonTimeout {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReasonTimeout();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReasonTimeout>): ReasonTimeout {
    return ReasonTimeout.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ReasonTimeout>): ReasonTimeout {
    const message = createBaseReasonTimeout();
    return message;
  },
};

function createBaseReasonSelfCheckout(): ReasonSelfCheckout {
  return {};
}

export const ReasonSelfCheckout: MessageFns<ReasonSelfCheckout> = {
  encode(_: ReasonSelfCheckout, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReasonSelfCheckout {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReasonSelfCheckout();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReasonSelfCheckout>): ReasonSelfCheckout {
    return ReasonSelfCheckout.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ReasonSelfCheckout>): ReasonSelfCheckout {
    const message = createBaseReasonSelfCheckout();
    return message;
  },
};

function createBaseMachineUsage(): MachineUsage {
  return { sessionId: "", checkIn: 0n, checkOut: 0n, reason: undefined };
}

export const MachineUsage: MessageFns<MachineUsage> = {
  encode(message: MachineUsage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.checkIn !== 0n) {
      if (BigInt.asIntN(64, message.checkIn) !== message.checkIn) {
        throw new globalThis.Error("value provided for field message.checkIn of type int64 too large");
      }
      writer.uint32(16).int64(message.checkIn);
    }
    if (message.checkOut !== 0n) {
      if (BigInt.asIntN(64, message.checkOut) !== message.checkOut) {
        throw new globalThis.Error("value provided for field message.checkOut of type int64 too large");
      }
      writer.uint32(24).int64(message.checkOut);
    }
    if (message.reason !== undefined) {
      CheckOutReason.encode(message.reason, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MachineUsage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMachineUsage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.checkIn = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.checkOut = reader.int64() as bigint;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = CheckOutReason.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MachineUsage>): MachineUsage {
    return MachineUsage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MachineUsage>): MachineUsage {
    const message = createBaseMachineUsage();
    message.sessionId = object.sessionId ?? "";
    message.checkIn = object.checkIn ?? 0n;
    message.checkOut = object.checkOut ?? 0n;
    message.reason = (object.reason !== undefined && object.reason !== null)
      ? CheckOutReason.fromPartial(object.reason)
      : undefined;
    return message;
  },
};

function createBaseMachineUsageHistory(): MachineUsageHistory {
  return { machineId: "", records: [] };
}

export const MachineUsageHistory: MessageFns<MachineUsageHistory> = {
  encode(message: MachineUsageHistory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.machineId !== "") {
      writer.uint32(10).string(message.machineId);
    }
    for (const v of message.records) {
      MachineUsage.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MachineUsageHistory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMachineUsageHistory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.machineId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.records.push(MachineUsage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MachineUsageHistory>): MachineUsageHistory {
    return MachineUsageHistory.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MachineUsageHistory>): MachineUsageHistory {
    const message = createBaseMachineUsageHistory();
    message.machineId = object.machineId ?? "";
    message.records = object.records?.map((e) => MachineUsage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUploadUsageRequest(): UploadUsageRequest {
  return { history: undefined };
}

export const UploadUsageRequest: MessageFns<UploadUsageRequest> = {
  encode(message: UploadUsageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.history !== undefined) {
      MachineUsageHistory.encode(message.history, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadUsageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadUsageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.history = MachineUsageHistory.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UploadUsageRequest>): UploadUsageRequest {
    return UploadUsageRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UploadUsageRequest>): UploadUsageRequest {
    const message = createBaseUploadUsageRequest();
    message.history = (object.history !== undefined && object.history !== null)
      ? MachineUsageHistory.fromPartial(object.history)
      : undefined;
    return message;
  },
};

function createBaseUploadUsageResponse(): UploadUsageResponse {
  return { success: false };
}

export const UploadUsageResponse: MessageFns<UploadUsageResponse> = {
  encode(message: UploadUsageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadUsageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadUsageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UploadUsageResponse>): UploadUsageResponse {
    return UploadUsageResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UploadUsageResponse>): UploadUsageResponse {
    const message = createBaseUploadUsageResponse();
    message.success = object.success ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
