/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ReportRouteImport } from "./routes/_report"
import { Route as MaterialRouteImport } from "./routes/_material"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ReportReportRouteImport } from "./routes/_report/report"
import { Route as AuthenticatedVisitRouteImport } from "./routes/_authenticated/visit"
import { Route as AuthenticatedUsageRouteImport } from "./routes/_authenticated/usage"
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile"
import { Route as AuthenticatedCompleteProfileRouteImport } from "./routes/_authenticated/complete-profile"
import { Route as MaterialMaterialAddRouteImport } from "./routes/_material/material.add"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: "/_report",
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRoute = MaterialRouteImport.update({
  id: "/_material",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportRoute = ReportReportRouteImport.update({
  id: "/report",
  path: "/report",
  getParentRoute: () => ReportRoute,
} as any)
const AuthenticatedVisitRoute = AuthenticatedVisitRouteImport.update({
  id: "/visit",
  path: "/visit",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: "/complete-profile",
    path: "/complete-profile",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const MaterialMaterialAddRoute = MaterialMaterialAddRouteImport.update({
  id: "/material/add",
  path: "/material/add",
  getParentRoute: () => MaterialRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/complete-profile": typeof AuthenticatedCompleteProfileRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/usage": typeof AuthenticatedUsageRoute
  "/visit": typeof AuthenticatedVisitRoute
  "/report": typeof ReportReportRoute
  "/material/add": typeof MaterialMaterialAddRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/complete-profile": typeof AuthenticatedCompleteProfileRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/usage": typeof AuthenticatedUsageRoute
  "/visit": typeof AuthenticatedVisitRoute
  "/report": typeof ReportReportRoute
  "/material/add": typeof MaterialMaterialAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/_material": typeof MaterialRouteWithChildren
  "/_report": typeof ReportRouteWithChildren
  "/login": typeof LoginRoute
  "/_authenticated/complete-profile": typeof AuthenticatedCompleteProfileRoute
  "/_authenticated/profile": typeof AuthenticatedProfileRoute
  "/_authenticated/usage": typeof AuthenticatedUsageRoute
  "/_authenticated/visit": typeof AuthenticatedVisitRoute
  "/_report/report": typeof ReportReportRoute
  "/_material/material/add": typeof MaterialMaterialAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/complete-profile"
    | "/profile"
    | "/usage"
    | "/visit"
    | "/report"
    | "/material/add"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/complete-profile"
    | "/profile"
    | "/usage"
    | "/visit"
    | "/report"
    | "/material/add"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_material"
    | "/_report"
    | "/login"
    | "/_authenticated/complete-profile"
    | "/_authenticated/profile"
    | "/_authenticated/usage"
    | "/_authenticated/visit"
    | "/_report/report"
    | "/_material/material/add"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  MaterialRoute: typeof MaterialRouteWithChildren
  ReportRoute: typeof ReportRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_report": {
      id: "/_report"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_material": {
      id: "/_material"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_report/report": {
      id: "/_report/report"
      path: "/report"
      fullPath: "/report"
      preLoaderRoute: typeof ReportReportRouteImport
      parentRoute: typeof ReportRoute
    }
    "/_authenticated/visit": {
      id: "/_authenticated/visit"
      path: "/visit"
      fullPath: "/visit"
      preLoaderRoute: typeof AuthenticatedVisitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/usage": {
      id: "/_authenticated/usage"
      path: "/usage"
      fullPath: "/usage"
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/complete-profile": {
      id: "/_authenticated/complete-profile"
      path: "/complete-profile"
      fullPath: "/complete-profile"
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_material/material/add": {
      id: "/_material/material/add"
      path: "/material/add"
      fullPath: "/material/add"
      preLoaderRoute: typeof MaterialMaterialAddRouteImport
      parentRoute: typeof MaterialRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedVisitRoute: typeof AuthenticatedVisitRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedVisitRoute: AuthenticatedVisitRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MaterialRouteChildren {
  MaterialMaterialAddRoute: typeof MaterialMaterialAddRoute
}

const MaterialRouteChildren: MaterialRouteChildren = {
  MaterialMaterialAddRoute: MaterialMaterialAddRoute,
}

const MaterialRouteWithChildren = MaterialRoute._addFileChildren(
  MaterialRouteChildren,
)

interface ReportRouteChildren {
  ReportReportRoute: typeof ReportReportRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportReportRoute: ReportReportRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  MaterialRoute: MaterialRouteWithChildren,
  ReportRoute: ReportRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
